### ISSUE TITLE
Instructions to install eventing v0.5 release are missing

### ISSUE THREAD

**Issue by abbi-gaurav** [knative/docs#1174]
## Expected Behavior
It seems the installation instructions for eventing are missing.
Referring to this link, I cannot find instructions to install eventing for v0.5.
https://github.com/knative/docs/tree/master/docs/eventing#installation

## Actual Behavior
There are instructions to install eventing v0.5.0

## Steps to Reproduce the Problem
Refer to the link https://github.com/knative/docs/tree/master/docs/eventing#installation

**Comment by Abd4llA** [comment]
seems to be available on [GKE](https://github.com/knative/docs/blob/master/docs/install/Knative-with-GKE.md) installation guide, but not in [minikube](https://github.com/knative/docs/blob/master/docs/install/Knative-with-Minikube.md). So we need to update the minikube doc

**Comment by samodell** [comment]
You can find instructions for install at https://www.knative.dev/docs/install/ 
You can refer to the "on any cluster" install guide: https://www.knative.dev/docs/install/knative-with-any-k8s/

Or you can always use the custom install page to pick and choose what set of components to install: 
https://www.knative.dev/docs/install/knative-custom-install/

The instructions for installing eventing were pulled off that page since it duplicate information that's contained in all the install guides.

**Comment by matzew** [comment]
I do find this confusing, tbh

**Comment by samodell** [comment]
@matzew  Especially since you're not the first person to find issue with this, I'd like to understand better.

So, the commands that were there just had the `kubectl apply` piece of it; they didn't touch on cluster setup or Istio install + config. Are you often installing (or re-installing) on a cluster that's already set up?

And when you found the commands missing, did you follow the link there to go to the install guides, or did that not seem like it'd have the info you want? Is it annoying that the commands for most of the install guides have all of the components together? Would you prefer to see the commands more separated out by component?

**Comment by samodell** [comment]
Also, I know we need to update the minikube guide so it also has the info for installing Build and Eventing -- do either of you (@matzew  or @abbi-gaurav ) have an opinion on switching from the current type of command that page uses for install:
```
curl -L https://github.com/knative/serving/releases/download/v0.5.0/serving.yaml \
  | sed 's/LoadBalancer/NodePort/' \
  | kubectl apply --filename -
```

to just the standard `kubectl apply --filename https://github.com/knative/serving/releases/download/v0.5.0/serving.yaml` commands that most of the other install guides use? I'm not sure when that `sed` command was added, or why.
