### ISSUE TITLE
Clearly define "help wanted" label

### ISSUE THREAD

**Issue by mhamwala** [knative/docs#1220]
## What is changing? (Please include as many details as possible.)
I'm unsure to what the difference is between the "help wanted" and "good first issue" labels are. on the website, we link to issues with the label "help wanted" but I have seen issues that are not "good first issues" with the "help wanted" label on them. I suggest that we link to issues that are "good first issue" on the website and use the "help wanted" for something else?. To me, good first issues connotate that help is wanted and these are much simpler issues to start with?

## How will this impact our users?
New contributors won't be discouraged from submitting PR's because some "help wanted" issues are too hard, and we will only have to use one label to indicate help for new contributors. 

## Context
Link to associated PRs or issues from other repos here.

1. #1066 
1. #1215

**Comment by samodell** [comment]
Main difference:

Something labeled with "help wanted" might be too complicated for a first-time contributor. It might be ambiguous, or otherwise difficult.

Something labeled with "good first issue" should be a very clearly defined problem, with clear information on what is needed to complete the task. "Good first issue"s should be very accessible to first-time contributors.
