### ISSUE TITLE
event delivery failed

### ISSUE THREAD

**Issue by rashiga** [knative/docs#1266]
All the pods in the knative namespaces are up and running.The pods for the Kuberneteseventsource and trigger is also up and running and the Broker is also configured. The kuberneteseventsource pod is showing the logs like 
{"level":"info","ts":1556768160.3738706,"logger":"fallback","caller":"kubernetesevents/adapter.go:113","msg":"Event delivery failed: error sending cloudevent: Status[400 Bad Request] ","eventID":"6774593f-6c8b-11e9-bfd1-a2564c89967f","sink":"http://default-broker.default.svc.cluster.local/"}
Please guide me how to go about this error.
 

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:
v0.5.0

**Comment by richard2006** [comment]
Firstly， I think we can look at the 0.5 version of the event processing model like this : 
![image](https://user-images.githubusercontent.com/10905381/57439959-b1bbe080-7279-11e9-892d-029a8e6ab6ff.png)
Secondly, the issue seems like the broker service is not worker, you can run `kubectl describe service default-broker`, and  check if the service  work fine.  And the `default-broker` is the `Ingress` component‘s k8s Service, actually。
And also, you can reference the  [eventing debugging](https://github.com/knative/docs/tree/master/docs/eventing/debugging)

**Comment by samodell** [comment]
For debugging help, you'll have better luck posting on our Slack channel or opening an issue in the related component, like Knative/Serving or Knative/Eventing. http://slack.knative.dev
