### ISSUE TITLE
Can not go from Broker->BrokerSpec->ChannelSpec (duck type hides the eventing ChannelSpec)

### ISSUE THREAD

**Issue by vaikas-google** [knative/docs#1280]
## Expected Behavior
In the Reference and API / Eventing API
Under the Broker, there's a BrokerSpec section and it refers to ChannelSpec, Clicking on that should take me to ChannelSpec that talks about how to specify a Provisioner, etc.. 

## Actual Behavior

Under the Broker, there's a BrokerSpec section and it refers to ChannelSpec, but it goes to Duck type for Channel spec, instead of the Channel.Spec which has things like Provisioner, etc. So, it's not possible to discover how to specify the ChannelProvisioner.

## Steps to Reproduce the Problem

1. https://knative.dev/docs/reference/eventing/#eventing.knative.dev
1. Click on Broker and BrokerSpec which takes you here: https://knative.dev/docs/reference/eventing/#BrokerSpec
1. Clicking on ChannelSpec takes you here: https://knative.dev/docs/reference/eventing/#ChannelSpec

## Additional Info
**Additional context**
Problem seems to be that there are two anchors called ChannelSpec, they should probably have duck.ChannelSpec and eventing.ChannelSpec, or just change the first ChannelSpec (duck one, to: duck.ChannelSpec) and leave the eventing one as ChannelSpec.

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by grantr** [comment]
https://github.com/ahmetb/gen-crd-api-reference-docs/pull/3 fixes this (by adding the package path to the fragment identifier)

**Comment by grantr** [comment]
@ahmetb is very busy with Kubecon prep and won't be able to merge https://github.com/ahmetb/gen-crd-api-reference-docs/pull/3 soon. We have a few options:

- Live with the breakage until @ahmetb is ready to merge the above change.
- Remove the eventing and eventing-sources reference docs, and point people to godoc.org instead.
- Temporarily update https://github.com/knative/docs/blob/cbc6652735630900fc037692a241506699fa7228/hack/gen-api-reference-docs.sh#L24-L26 to point to `https://github.com/grantr/gen-crd-api-reference-docs`. That would fix this issue now, and we can repoint back to the parent repo when the fix is merged. There's a risk that the link format might change in between such that external links into the reference docs might break, taking the user to the top of the page instead of directly to the desired heading.

What do you prefer @samodell?

**Comment by ahmetb** [comment]
I vote for option #1.

But if you can send me a quick PR + rendered markdown file in a gist, I'd be happy to review.

**Comment by grantr** [comment]
> if you can send me a quick PR + rendered markdown file in a gist, I'd be happy to review.

https://github.com/ahmetb/gen-crd-api-reference-docs/pull/3 is the quick PR :)

The templates actually generate html, not markdown. I created a gist of the output. You can see the changes at https://gist.github.com/grantr/f08e59a4601c9ca6ab5d53c84759cb93#file-eventing-html-L80 and https://gist.github.com/grantr/f08e59a4601c9ca6ab5d53c84759cb93#file-eventing-html-L52. I'm not sure how to get that to render. You may need to download the files and open them in the browser.


I'm not sure how to make

**Comment by ahmetb** [comment]
@grant if you rename the .html to .md it will render correctly.

`#github.com/knative/eventing/pkg/apis/duck/v1alpha1.ChannelSpec` doesn't solve the problem. We should have something like `#eventing_knative_dev_v1alpha1_ChannelSpec`.

If you can update the PR to do that, I'm happy to accept.

Right now your PR will take us to a place where we’ll be susceptible to #target links breaking are pretty frequently, which is a worse place than we already are.

**Comment by grantr** [comment]
@ahmetb nice, renaming to .md fixed the rendering. Pro tip:tm:

I'll see if I can change the identifiers to use apiVersion instead.

**Comment by samodell** [comment]
The issue Ville pointed out is fixed now on the live site, so closing this out.

https://knative.dev/docs/reference/eventing/#eventing.knative.dev
