### ISSUE TITLE
Update Minikube, Minishift, Openshift, and Docker for Mac instructions for installing istio

### ISSUE THREAD

**Issue by samodell** [knative/docs#1319]
In 0.6, Knative stopped providing .yaml files for installing Istio. We created the Installing Istio for Knative guide instead, and want folks to either manually install Istio themselves or use a managed Istio installation provided by their chosen cloud platform.

There are a few of the guides that were customizing the Istio installation extensively, and I am not 100% sure how to pull out the instructions for using our provided Istio files without losing important steps.

- Minkube, Openshift, and the Docker for Mac guides are all swapping LoadBalancer for NodePort during instllation

- OpenShift has additional instructions around installing Istio.

- Minishift has a few customization steps.

Opening this issue to track that these guides still need to be updated to remove references to installing Istio using Knative-provided .yaml files.

**Comment by bbrowning** [comment]
We're discussing the best way to handle this for OpenShift. The official way we're supporting installation of Knative Serving on OpenShift is to install it via our Operator, which can be installed with a single `kubectl apply` (or `oc apply`) command. That Operator will automatically install a minimal Istio configured appropriately on behalf of the user if one isn't already installed and then install the rest of Knative Serving.

That's the simplest option from a user's point-of-view to get a working Knative Serving on OpenShift. We have a similar Operator for Knative Eventing as well.

Is there a preference that we maintain explicit Istio installation instructions for OpenShift? And explicit Knative installation instructions by using the Knative release yamls directly instead of consuming them via our Operator?

We have a very simple installation experience for OpenShift, but it does use some OSS artifacts that are not yet produced by the Knative community directly to achieve yet.

**Comment by samodell** [comment]
I think that's great. As platforms build these operator install options, we
should link out to where users can find those and perhaps stop delivering
install instructions for that platform here. It makes more sense to replace
it with a link to the docs for using whatever operator.

I don't think that applies to minikube or Docker for Mac, though.

**Comment by abrennan89** [comment]
@samodell  just to clarify the approach we want to take - are we saying that we should link out from the OpenShift docs at knative.dev (when updated) to the process for installing Istio as a dependency?

I don't see how this is possible if the same Operator that installs all the rest of the Serving components on OpenShift installs Istio, since it's only one command to run this and cover all of these together. Wouldn't it be better to just add a note that states that the Serving Operator on OpenShift installs x Knative dependencies and then list these?
