### ISSUE TITLE
Community samples need to be updated for Serving 0.6

### ISSUE THREAD

**Issue by dgerd** [knative/docs#1330]
**Describe the change you'd like to see**
https://github.com/knative/docs/tree/master/community/samples/serving demonstrate using the new API shapes introduced in Serving 0.6

**Additional context**
Serving 0.6 updated the recommended API fields for Services. The examples were updated in https://github.com/knative/docs/tree/master/docs/serving/samples, but this directory was missed.

**Comment by RichieEscarez** [comment]
Thanks for the issue @dgerd. The `/community/samples/` are not something that the docs team is committed to regularly updating as a high priority. Since we have such a large back log of other priority items, we hope that the community can step in and help maintain this content, which will allow us to be more effective across other content gaps (including some of the website related items).

This is definitely not something that we intend on ignoring but it is something that must come after several other and higher priority items. If you are interested, we would be happy to review a PR if you sent one over? 

/cc @samodell

**Comment by dgerd** [comment]
Opened a PR. I do not have the time to go through and build all of the samples to ensure that they still work, but this should update them all to use the new v1beta1 format for both the README and YAML files. This should help users get started down the right path instead of a deprecated one.

The fix should be cherry-picked into 0.6 as well as applied to head.
