### ISSUE TITLE
The commands to find IP address of the ingress gateway don't work on AWS

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#1376]
When you install Kubernetes to EKS or AWS EC2, the Service (type:LoadBalancer) of `istio-ingressgateway` won't get an IP address.

Instead it'll get a `.hostname` field. This is different than most providers. It's described at https://eksworkshop.com/deploy/viewservices/

This difference is making Knative samples/docs very hard to use for users on AWS.

We need to change these `.ip` usages to something that falls back to `.hostname` field when it's missing.

```
docs/install/getting-started-knative-app.md:118:   export IP_ADDRESS=$(kubectl get svc $INGRESSGATEWAY --namespace istio-system --output 'jsonpath={.status.loadBalancer.ingress[0].ip}')
docs/install/Knative-with-Minishift.md:296:export IP_ADDRESS=$(oc get svc $INGRESSGATEWAY -n istio-system -o 'jsonpath={.status.loadBalancer.ingress[0].ip}')
docs/serving/samples/telemetry-go/README.md:172:export SERVICE_IP=`kubectl get svc $INGRESSGATEWAY --namespace istio-system --output jsonpath="{.status.loadBalancer.ingress[*].ip}"`
docs/serving/samples/rest-api-go/README.md:172:   --output jsonpath="{.status.loadBalancer.ingress[*].ip}"`
docs/serving/samples/hello-world/helloworld-java-spring/README.md:198:   --output jsonpath="{.status.loadBalancer.ingress[*].ip}")
docs/serving/samples/hello-world/helloworld-java-spark/README.md:150:     --output jsonpath="{.status.loadBalancer.ingress[*].ip}")
docs/serving/samples/hello-world/helloworld-kotlin/README.md:209:     --output jsonpath="{.status.loadBalancer.ingress[*].ip}")
docs/serving/samples/autoscale-go/README.md:50:     export IP_ADDRESS=`kubectl get svc $INGRESSGATEWAY --namespace istio-system --output jsonpath="{.status.loadBalancer.ingress[*].ip}"`
docs/serving/samples/thumbnailer-go/README.md:188:export SERVICE_IP=`kubectl get svc $INGRESSGATEWAY --namespace istio-system --output jsonpath="{.status.loadBalancer.ingress[*].ip}"`
docs/serving/samples/grpc-ping-go/README.md:44:   export SERVICE_IP=`kubectl get svc istio-ingressgateway --namespace istio-system --output jsonpath="{.status.loadBalancer.ingress[*].ip}"`
docs/serving/samples/build-private-repo-go/README.md:193:    --output jsonpath="{.status.loadBalancer.ingress[*].ip}")
docs/serving/samples/buildpack-function-nodejs/README.md:82:$ export SERVICE_IP=`kubectl get svc $INGRESSGATEWAY --namespace istio-system --output jsonpath="{.status.loadBalancer.ingress[*].ip}"`
docs/serving/samples/buildpack-app-dotnet/README.md:84:export SERVICE_IP=`kubectl get svc $INGRESSGATEWAY --namespace istio-system --output jsonpath="{.status.loadBalancer.ingress[*].ip}"`
community/samples/serving/helloworld-java-quarkus/README.md:272:     --output jsonpath="{.status.loadBalancer.ingress[*].ip}")
```

**Comment by houshengbo** [comment]
@ahmetb  Do you what the command is for AWS to get the IP? If so, would you mind fixing it with a PR?

**Comment by ahmetb** [comment]
As I said above `.hostname` field has the value. It's not an IP address but rather a FQDN as the linked article explains.

I might be able to fix it if I can find the time. I bet there's a nifty JSONPATH if else syntax that lets doing this simpler.

**Comment by ahmetb** [comment]
One solution I found was to do

    --output=jsonpath="{.status.loadBalancer.ingress[0]['hostname','ip']}"

but this would break if both `hostname` and `ip` fields exist at the same time. I'm not sure if any k8s distro does that right now. @mattmoor do you see any cleaner solutions here?

**Comment by samodell** [comment]
@ahmetb  If you don't have time to implement the solution you suggested, could you open an issue in Serving to suggest someone else do it?

**Comment by ahmetb** [comment]
Waiting input from @mattmoor.
Not sure what's the right --jsonpath option here.

**Comment by mattmoor** [comment]
IDK of a cleaner solution, not do I know of a provider for which the command you have given breaks.

**Comment by ahmetb** [comment]
In that case we should still keep it open unless we fix. It will be a problem for almost everyone using Knative on AWS for the first time.

**Comment by tcnghia** [comment]
@ahmetb since we are not aware of a distro where your command breaks, let's update to use it?  if it breaks someone we can rollback.  

My guess is that this change will be a net positive, since the corner-case K8s distribution may represent small set of user?  Again, if the guess is wrong we can rollback.

**Comment by mattmoor** [comment]
I'd like to better understand where we still have this, but more because we shouldn't have Istio specific stuff outside of install, which itself no longer uses this.  I don't think that it's unreasonable to expect that folks have set up DNS (possibly thru `xip.io`).  Ack that `xip.io` doesn't work on AWS, but DNS also isn't that hard to set up.

**Comment by abrennan89** [comment]
If this is something that's specific to AWS, should we be documenting it at all? If it's something that needs to be configured to use Knative on a particular platform, it should be in AWS's own docs I would think.
@carieshmarie any thoughts?

**Comment by ahmetb** [comment]
It’s not necessarily AWS specific but the way AWS does networking exposes this situation. The feature is supported and allowed in Kubernetes, so there might be other cases where this’ll happen.

**Comment by abrennan89** [comment]
After discussion on this in Slack with @mattmoor , the solution we've come to is to ensure that all samples point to "ensuring you have a working Knative installation" of the required components before you begin. The install docs for Serving already call out configuring a DNS as far as the scope of our docs go.

Work required: review the sample, remove any steps like this and point to correct section of docs as prerequisites instead.

**Comment by abrennan89** [comment]
This issue has been open for ~2 years and the fix to add "make sure you have a working installation of Knative" to every sample seems very trivial / not worth spending docs resources on to me atm, since it should be assumed that a working Knative is required to use the samples IMO.

@omerbensaadon has been working on standardizing prerequisites in docs, and I have been working on cleaning up sample docs to move them into a proper structure as part of the rest of the site, so I am going to close this issue since I think it will be resolved as we improve the docs structure generally.

If this is still an issue, **please raise an issue requesting a specific docs change, with a link to the section/page, that will fix the problem**, or feel free to add a PR.
