### ISSUE TITLE
Add reference / section for Knative `kn` Client CLI

### ISSUE THREAD

**Issue by maximilien** [knative/docs#1555]
[github.com/knative/client](https://github.com/knative/client)

**Describe the change you'd like to see**

* Add a section on the Client in the Knative docs

Since the Knative `kn` client CLI is readying it’s second release, and we would like to have more folks tinkering with it and get Knative users to start using it, I wonder if it’s time to ?

* Start adding references to the `kn` client CLI in places where `kubectl` is being used. 

Perhaps in addition to `kubectl` in places where both can be used.

**Additional context**

I’d also be happy to see what your plans are with adding the `kn` client CLI in the docs. 

Perhaps you’ve already discussed and waiting for more stable releases? If not, let’s discuss in this issue. 

Even some outline on what you need as I may be able to help you.

**Comment by samodell** [comment]
cc @sixolet 

I had been in touch with Naomi a bit about this, but we didn't come to a final conclusion.

For now, I would love to see the docs for using `kn` (https://github.com/knative/client/tree/master/docs) moved into the Docs repo. I'm happy to help out with that.

I don't think we should recommend `kn` as the primary way to interact with Knative until it works with Eventing as well as Serving, since that would complicate things quite a bit. Looks like this issue is tracking Eventing support in `kn`: https://github.com/knative/client/issues/217

**Comment by RichieEscarez** [comment]
[Proposed location in the site nav](https://docs.google.com/spreadsheets/d/1L3EAeTX7RRdZhcQZeNmxwN4DCncuImCXA5A1_KQvwSk/edit#gid=413198505&range=197:197)

**Comment by abrennan89** [comment]
kind/needs-end-input

**Comment by abrennan89** [comment]
kind/needs-eng-input

**Comment by abrennan89** [comment]
/kind/needs-eng-input

**Comment by abrennan89** [comment]
@rhuss I'm going to go ahead and manually add CLI docs until we can figure out the automation part - I think it's better than nothing for now? :woman_shrugging: wdyt?

**Comment by rhuss** [comment]
yes, sure ! thanks ...

**Comment by abrennan89** [comment]
There is now a CLI topic in the main navigation: https://knative.dev/development/client/
We can add docs for specific `kn` commands as we go, I am going to close this issue in favor of opening smaller issues for adding specific CLI docs, since with an issue this general its hard to know when we can call it complete.

Thanks for raising @maximilien and please feel free to add additional `kn` CLI doc issues for documenting specific tasks / commands.

**Comment by abrennan89** [comment]
Epic for additional CLI tasks: https://github.com/knative/docs/issues/3346
