### ISSUE TITLE
Create a glossary of terms with definitions

### ISSUE THREAD

**Issue by labadav** [knative/docs#170]

**Comment by aslom** [comment]
This is excellent idea especially for more technical parts such as defining components in Knative projects.

For example defining queue-proxy:
https://github.com/knative/serving/blob/08b386d8fbcef2751cd2cc221098526354da4d37/docs/scaling/SYSTEM.md
https://github.com/knative/serving/pull/7126

**Comment by omerbensaadon** [comment]
Started here: https://docs.google.com/spreadsheets/d/1p1_kBUd6ZvonxHkMcEJPayf6QIpExuFf5cFq0ptar7I/edit#gid=0

**Comment by abrennan89** [comment]
> Started here: https://docs.google.com/spreadsheets/d/1p1_kBUd6ZvonxHkMcEJPayf6QIpExuFf5cFq0ptar7I/edit#gid=0

I don't really think this is a glossary; it's just for the style guide and doesn't actually contain descriptions of what the words are / mean

**Comment by omerbensaadon** [comment]
Ah, I stand corrected, could be a good place to source words from though!

**Comment by abrennan89** [comment]
Added a doc to collect terms that need definitions and possibly snippets: https://docs.google.com/spreadsheets/d/1ayoHb0Y833smQzIoe_Cj9NqwxaHpaYvaJ2tYtk3xw7A/edit?usp=sharing

**Comment by soham283** [comment]
@abrennan89 I would like to work on the issue, can you please assign this issue to me?
(the changes must be done into word list page or on the spreadsheet which you have mentioned above?)

**Comment by abrennan89** [comment]
@soham283 thanks! I don't think we ever decided where it should live, I think I may have deleted the old file since I never really got anywhere with it, so feel free to create any kind of document on the Google Drive for Knative that suits you (spreadsheet might be easiest or doc) to collect information and then we can decide where this will live later.

@snneji @omerbensaadon was a glossary included anywhere in the card sort, or should this live in github etc maybe?

**Comment by soham283** [comment]
@abrennan89  I would like to do it on Spreadsheet.
 I have one query, I should start writing glossary by referencing only word list  or I have to go through from some different list??

**Comment by snneji** [comment]
> @snneji @omerbensaadon was a glossary included anywhere in the card sort, or should this live in github etc maybe?

No, the glossary is not on the card sort. It can be put wherever you think best.

**Comment by abrennan89** [comment]
> No, the glossary is not on the card sort. It can be put wherever you think best.

I think it should live wherever other reference docs end up being then I guess, but I think it would be better to add it to the card sort since it's something that was requested by users. Up to you.

@soham283 this is actually not at all related to the word list, the word list is a reference list for technical writers and does not necessarily only include technical terms. The ask for creating a glossary is to gather all the FAQ words related to Knative specifically and explain them. I don't really have any advice on how to gather this, so I'll let @snneji or @omerbensaadon take it from here.

**Comment by abrennan89** [comment]
@soham283 are you still planning to work on this one?

**Comment by snneji** [comment]
Hi @soham283, are you still planning to do this? If not we will take your name off and offer it to others to work on.

**Comment by abrennan89** [comment]
Discussed in the Docs WG today.
It seems impractical to add and maintain a glossary for Knative, especially since this issue was opened ~4 years ago and we can't seem to gather any user input about which terms should actually be documented.

Instead, the Docs WG plan to look into creating better conceptual information in the docs so that it's clear what different terms mean on a case by case basis, either similarly to Kubernetes documents concepts (https://kubernetes.io/docs/concepts/) or just by improving conceptual info throughout the docs.
