### ISSUE TITLE
Update Knative Installation instructions to include Eventing

### ISSUE THREAD

**Issue by akashrv** [knative/docs#1853]
[Installing Knative](https://knative.dev/docs/install/) only talks about installing Knative Serving. There are no instructions to install Knative Eventing except for in a small section under [Getting Started](https://knative.dev/docs/eventing/getting-started/#installing-knative-eventing)

Knative Eventing and Serving are independent components and can work together too. My suggestion will be to have two separate pages for Install Knative Serving, and Install Knative Serving. Rename the current  [Installing Knative](https://knative.dev/docs/install/) page to Install Knative Serving. Have both these pages under "Installing Knative", page and change its content accordingly.

**Comment by samodell** [comment]
@akashrv 

Currently, the install guides there direct folks to install both Knative Serving and Eventing --

https://knative.dev/docs/install/knative-with-gke/#installing-knative

The majority of the install guides follow that lead. (The ones that don't are for platforms with minimal disk space, where size constraints were an issue).

We want to avoid duplicating the install page for each component and then multiplying that by an install page per-platform. We could do a better job at communicating on the install home page that all components are installed by the guides, though. 

I also think the Istio/Gloo requirements have changed a bit since those guides were written; I think now Eventing has no hard networking dependency, right? So it's possible to install just Knative Eventing, without Istio or Gloo? That language also needs to be updated. But I do want to avoid making duplicate guides just for eventing.

**Comment by akashrv** [comment]
There are two issues I see here:

1. Not all install guides cover Eventing
https://knative.dev/docs/install/knative-with-ambassador/
My Bad :( - I just read the first link and didnt check others. You are correct. Other links mention both.

2. It is not clear to someone not working on Knative whether Serving and Eventing are independent or not. These are independent components and we should clarify it to end users in our installation guide. Whether we create separate pages, or clarify this on a single page - I will leave it to docs team who are experts on this. But please make it clear to end users that they can install either Serving or Eventing or Both. @samodell Let me know your thoughts.

**Comment by vaikas** [comment]
@akashrv I'm closing this since we have install instructions. Please reopen if you still think it's an issue?
