### ISSUE TITLE
Setup TLS with Gloo gateway

### ISSUE THREAD

**Issue by onsails** [knative/docs#1886]
I am writing an blog post about setting up GKE cluster, installing Knative with Gloo and deploying a service. Trying to make my instructions appropriate for production use and understandable for newcomers to k8s like I am. I've successfully done and described all steps (deployed gloo and knative, deployed a service available on HTTP with explicit health and readiness, database connection configuration, ClusterIssuers with let's encrypt) except TLS exposing setup.

## Expected Behavior

After going through installation steps in gloo part and TLS setup service is available on https.

## Actual Behavior

TLS setup only covers Istio case. There is no obvious way to setup TLS with Gloo on Knative.

There is an instruction how to setup TLS in Gloo docs but it assumes Gloo installed without Knative integration which adds some abstraction layer, it's configuration is not described for TLS part as well.

**Comment by tcnghia** [comment]
@prettynatty AutoTLS is still in its early phase, but it works with Gloo.

/cc @ilackarms is there an easy way to manually assign certificates for Gloo?

**Comment by prettynatty** [comment]
I'l happily contribute to docs of both knative and Gloo about TLS setup, even if there is no easy way to setup TLS. We've discussed the issue with @ilackarms in Gloo slack for a while and apparently there are multiple ways to setup TLS on Knative with Gloo. Then moved conversation here to involve both sides because I decided to stick to the way which allows developer to keep using Knative abstractions more than Gloo to "enable developers to focus on what matters" (c) https://knative.dev more than to leverage Gloo specifics. But it's not obvious, for example, which `clusteringress.class` value should be? Should `istio.sidecar.includeOutboundIPRanges` be omitted when you go with Gloo? What' should be there instead of Istio.* arguments? Is it event possible for now to instruct knative use TLS with Gloo by just editing configmap `config-network` or user should setup Gloo VS and gateway manually?

**Comment by abrennan89** [comment]
@onsails is this issue still relevant?

TLS is covered now here https://knative.dev/docs/install/any-kubernetes-cluster/#optional-serving-extensions but it's not clear to me what the request is in this issue for docs, so I'm not sure if this covers it?

**Comment by onsails** [comment]
No, lots of things changed since I created the issue.
TLS setup instructions are clear now.
