### ISSUE TITLE
does knative serving support faas？

### ISSUE THREAD

**Issue by etherlai** [knative/docs#1910]
I see serving sample yaml image is a server with 8080 port.
can I use function not web server just like kubeless.

**Comment by vaikas-google** [comment]
Yes you can create functions that behave like web servers, and wire them into events. I think you're maybe asking are there libraries that mask away the invocation (http[s] as a transport for example) instead of having to hand code it?
Here's some examples for how to use Knative eventing:
https://knative.dev/docs/eventing/samples/

There are some tools that make it easier to write function logic:
https://github.com/cloudevents/sdk-go
https://github.com/cloudevents/

Does that help?

**Comment by samodell** [comment]
Closing this out since Ville provided an answer.
