### ISSUE TITLE
Ensure that all content affected by the nav changes gets a "redirect"

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1925]
The following requires a redirect:
- moved or changed folders
- filename change

To add a redirect, you must add the [`aliases` element](https://gohugo.io/content-management/front-matter/#front-matter-variables) to the file's frontmatter.

**`aliases:`**
**`  - /docs/contribution-guidelines/`**

[Example](https://raw.githubusercontent.com/knative/docs/6efd60b4a000ba4293cc694755738366b5ef059d/contributing/_index.md)

```
---
title: "Knative contribution guidelines"
linkTitle: "Contributing"
weight: 20
type: "docs"
aliases:
  - /docs/contribution-guidelines/
---
```

**Comment by abrennan89** [comment]
@carieshmarie I'm not sure it's worth having a single issue tracking this. I doubt anyone will / is able to go through every file and check that they've been redirected, since how would one even know the file had moved unless there's a broken link or something somewhere?

I recommend closing this but lmk what you think :woman_shrugging:
