### ISSUE TITLE
Getting Started with Eventing(docs/eventing/getting-started.md)

### ISSUE THREAD

**Issue by justingrayston** [knative/docs#1926]
## Expected Behavior
In the docs it says `kubectl get pods -n knative-eventing` will result in

NAME                                            READY   STATUS    RESTARTS   AGE
eventing-controller-6cdf6ff785-44k98            1/1     Running   0          29m
eventing-webhook-6c4f6699d8-qclbx               1/1     Running   0          29m
imc-controller-85cdb4946b-h2msj                 1/1     Running   0          13m
imc-dispatcher-5f4689d868-fspt6                 1/1     Running   0          13m
in-memory-channel-controller-d9db9d879-f2jw6    1/1     Running   0          13m
in-memory-channel-dispatcher-79bc7f46cd-4mvj6   1/1     Running   0          13m
sources-controller-5847564f4f-z59xc             1/1     Running   0          29m

## Actual Behavior
I get...
```
eventing-controller-db9b58855-5g24d   1/1     Running   0          2d
eventing-webhook-595c6b4fd8-hkm5k     1/1     Running   0          47m
imc-controller-7b9b7f9f66-4q6s6       1/1     Running   0          2d
imc-dispatcher-775c96b5b5-cwd4h       1/1     Running   0          2d
sources-controller-78655cd9f9-njbhh   1/1     Running   0          2d
```

## Steps to Reproduce the Problem
Install Knative 0.9.0 on GKE as per the instructions, run the command. I am guesting imc stands for "in memory channel" and if so, in the docs what is the difference between the long and short form pods?

**Install information:**
 - Platform: GKE
 - Knative Version: 0.9.0

**Comment by samodell** [comment]
At first, the guide directed folks to install eventing using from the `eventing.yaml` file, instead of the `release.yaml` file. Only the `release.yaml` file comes with the inmemory cluster channel provisioner. The instructions now point to installing `release.yaml` (https://github.com/knative/eventing/releases/download/v0.11.0/release.yaml), which does come with the channel provisioner. Closing this out as fixed.
