### ISSUE TITLE
Can't find old documentation pages about using private registries

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#2025]
These pages showing up on site search results for keyword "private"  seem to be gone and redirect to the homepage :( (why can't we set up redirect while shuffling files like this in Netlify?)

There's nothing under `Serving Component` on the sidebar that helps me find where this content has gone to.

> ![image](https://user-images.githubusercontent.com/159209/70275185-77101d00-1762-11ea-9d54-d6691fb25e1d.png)

**Comment by ahmetb** [comment]
Sadly all google search results are broken, too. The content at #847 seems to be gone from the site.

![image](https://user-images.githubusercontent.com/159209/70275303-bd657c00-1762-11ea-8830-7910cf53f02e.png)

**Comment by RichieEscarez** [comment]
Re: #847
 
That content uses Knative Build, which was deprecated. To view that file, you can view the past doc versions in the GitHub repo (along with the deprecated Knative Build content):

https://github.com/knative/docs/branches/all

**Comment by RichieEscarez** [comment]
Good news is that I'm not able to get those same search results (likely since our site index was updated and scraped between now and when this issue was opened):

![image](https://user-images.githubusercontent.com/11762685/71935997-16a73d80-315d-11ea-99ee-8055bf586737.png)

The new version of "how to ... private registry" file (from #2027) now shows at the top so im going to close this and also ensure that we are more strict about using "redirects".

Thanks @ahmetb!

**Comment by ahmetb** [comment]
I'm seeing no results from knative.dev yet but I'll take your word for it. 

![image](https://user-images.githubusercontent.com/159209/71937627-d1393f00-3161-11ea-8721-a71843d09aee.png)

**Comment by RichieEscarez** [comment]
Maybe a chrome history "thing" so I see recently visited pages that match the search query?

I was trying to replicate that query from your screenshot so that I could obtain those URLs that result in 404s and then add them as aliases in the new file. Feel free to pass along any other bad URLs that you come across and i'll happily add them to the frontmatter our current source files.
