### ISSUE TITLE
Istio deprecating helm install

### ISSUE THREAD

**Issue by Namphibian** [knative/docs#2199]
Just a note that Istio is deprecating helm installs of the service mesh.

See here:
https://istio.io/docs/setup/install/helm/

The current documentation show the helm install, however if you go to the Istio site the instructions are different.

Its worth to note that most of the configuration stays the same when using the recommended install. I will see if I can get it running and make some suggestions.

**Comment by samodell** [comment]
@tcnghia  Can you or someone else with networking expertise decide how we should tell users to perform the Istio install once install via Helm is deprecated? Related to #2166 , where Matt suggests maybe we should work with the Istio folks to create a Knative profile for Istio install.

**Comment by Namphibian** [comment]
@samodell 

I tried using the minimal profile instead of the Helm install with everything switched off and it worked pretty well.

They might be able to base their instrructions on the different profiles plus apparently you most of the helm properties are available by appending value to the front of it.

See the snippet below:

If you want to enable security on top of the default profile, you can set the security related configuration parameters:

`$ istioctl manifest apply --set values.global.mtls.enabled=true --set values.global.controlPlaneSecurityEnabled=true
`

In general, you can use the --set flag in istioctl as you would with Helm. The only difference is you must prefix the setting paths with values. because this is the path to the Helm pass-through API, described below.

**Comment by abrennan89** [comment]
Docs still mentioning needing Helm for the Istio install: https://knative.dev/docs/install/installing-istio/

Is there a reason why we provide specific Istio docs for Knative, rather than listing it as a prerequisite in our install docs, linking out to the official guide, then just having a "post-install config" type section about configuring it to work?

cc @markusthoemmes @mattmoor any thoughts? Not sure who is the best person to advise here.

**Comment by evankanderson** [comment]
Fixed by #2458
