### ISSUE TITLE
Installing Knative(development/install/knative-with-any-k8s.md): Broken link for broker implementation

### ISSUE THREAD

**Issue by josiemundi** [knative/docs#2208]
## Expected Behavior
Following the command in the Installing Knative docs, when I run:

```kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.12.0/channel-broker.yaml```

I expect this to install a Broker implementation. 

## Actual Behavior

When I run above command I get the following 404 error:

error: unable to read URL "https://github.com/knative/eventing/releases/download/v0.12.0/channel-broker.yaml", server reported 404 Not Found, status code=404"

I don't think this yaml exists.

## Steps to Reproduce the Problem

1. Run ```kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.12.0/channel-broker.yaml``` 

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by samodell** [comment]
Hey @josiemundi ! One thing with the pre-development docs in that they in active development, so it's possible that there is no channel-broker.yaml for v0.12, but that it will exist in v0.13. (The master branch becomes the next release branch when the release is cut.) I don't know for sure if that's the case with this error, but it may be. @vaikas , since this is eventing-related.

**Comment by mpetason** [comment]
It looks like the issue follows what @samodell was saying. It doesn't exist in v0.12 but does in v0.13. 

This link works - 

https://github.com/knative/eventing/releases/download/v0.13.0/channel-broker.yaml

Now the docs are updated to show the correct link after the v0.13.0 release.
