### ISSUE TITLE
First Eventing Example is Too Complicated

### ISSUE THREAD

**Issue by sebgoa** [knative/docs#2234]
**Describe the change you'd like to see**

The landing page points to an eventing example that deals with the kubernetes event source. I think it is too complicated.

A simple cronjob event source should suffice. It would avoid having to setup service accounts and role binding for the k8s source to work.

**Additional context**

Just going through the first 4 examples of the landing page.

**Comment by abrennan89** [comment]
@sebgoa can you please provide a link for the landing page you're talking about - is it this https://knative.dev/development/eventing/samples/ ?
This page is meant as a reference doc, and I don't think the samples are in any particular order. At any rate, they should probably all be moved into the actual related section of docs eventually, so I don't think it's worth expending much effort on this.

**Comment by sebgoa** [comment]
The landing page here: https://knative.dev/docs/

The fourth sample is the eventing one and goes to:
https://knative.dev/docs/eventing/samples/kubernetes-event-source/


<img width="893" alt="Screenshot 2020-06-30 at 18 43 57" src="https://user-images.githubusercontent.com/1886299/86153266-af61b900-bb01-11ea-9d99-5792b60c00dd.png">

**Comment by abrennan89** [comment]
Ah, I understand now.
I think this should link to https://knative.dev/docs/eventing/sources/ - however, that page probably needs a lot of work too.

When I land here, I would expect:

- An explanation of event sources and how they work
- A list of core/supported event sources
- Subsections for examples of each event source type

@carieshmarie FYI - event sources should be a consideration when we're talking about roadmap planning next week, since it's a particularly messy section of docs IMHO.
