### ISSUE TITLE
Installing cert-manager for TLS certificates(docs/serving/installing-cert-manager.md)

### ISSUE THREAD

**Issue by richterdavid** [knative/docs#2359]
##  Expected Behavior

Documented install procedure at https://knative.dev/docs/serving/installing-cert-manager/ works fine.

## Actual Behavior

~/knative-workspace/cert-manager-0.6.1$ kubectl apply -f deploy/manifests/cert-manager.yaml
unable to recognize "deploy/manifests/cert-manager.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "deploy/manifests/cert-manager.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
~/knative-workspace/cert-manager-0.6.1$ kubectl apply -f deploy/manifests/cert-manager.yaml --validate=false
unable to recognize "deploy/manifests/cert-manager.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "deploy/manifests/cert-manager.yaml": no matches for kind "Deployment" in version "apps/v1beta1"

**Install information:**
 ~/knative-workspace/cert-manager-0.6.1$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.3", GitCommit:"c05f43a760f4388351a70ca90bdf876609148f14", GitTreeState:"clean", BuildDate:"2020-03-18T22:49:20Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}

Running against GKE on GCP, master version 1.16.8-gke.3 & node pool version 1.16.6-gke.18

$ kubectl get namespace knative-serving -o 'go-template={{index .metadata.labels "serving.knative.dev/release"}}'
v0.11.0-gke.9
$ kubectl get namespace knative-eventing -o 'go-template={{index .metadata.labels "eventing.knative.dev/release"}}'
v0.13.0

**Comment by mpetason** [comment]
This is due to an older apiVersion in the cert-manager deployment files. The cert-manager.yaml and others are using apps/v1beta1 while the latest version of K8s uses apps/v1.

That being said, the current version of Cert-Manager uses helm, so I'm not sure which version we want to point to in the docs or if we should rewrite to work with the helm installation.

**Comment by mpetason** [comment]
This page actually needs to be updated a bit. The latest version of cert-manager is v0.14.1, and we're recommending v0.6.*, which probably will not as well as we need. It's not a simple "update URL for crds/other" because it swaps to Helm, which means the YAML files are dependent on the values provided by Helm.

**Comment by ZhiminXiang** [comment]
Currently we run our E2E tests against cert-manager 0.12. So I will update the doc to upgrade to 0.12. Once we test 0.14, we can bump the version to 0.14.

**Comment by ZhiminXiang** [comment]
This issue has been partially addressed by PR https://github.com/knative/docs/pull/2239/files.

I will update the supported version to 0.12 next.
