### ISSUE TITLE
Productionize and public target burst capacity document.

### ISSUE THREAD

**Issue by vagababov** [knative/docs#2375]
The document: https://docs.google.com/document/d/1ubszZxikwe0O1JsA-Rjwdv3YA-rgHWKLI9WPAD083ig/edit

I took it to the WG meeting some time ago.
This should give it proper tracking.

/cc @abrennan89

**Comment by abrennan89** [comment]
This issue is blocked pending merge of #2439 which adds TBC to the docs, which we will expand on in this issue by adding a load balancing section.
The PR that needs to be merged already has an approved label, so it just needs an LGTM I think.

@carieshmarie @mattmoor @evankanderson could someone with permissions take a look at merging #2439 please to unblock this. Thanks!

**Comment by abrennan89** [comment]
TBC has been added to the docs https://knative.dev/development/serving/autoscaling/target-burst-capacity/
but more work is required re load balancing docs to move this to the correct place.

**Comment by abrennan89** [comment]
Dependency on #2477 - work on these together

**Comment by abrennan89** [comment]
Closing this issue @vagababov because everything else should be covered by the two PRs I've linked by the time the second one is merged :slightly_smiling_face: thanks for providing this info.
