### ISSUE TITLE
Page needs improvement

### ISSUE THREAD

**Issue by blorette** [knative/docs#2415]
## Documentation Unlear
Step 3 makes reference to applying service account when above simply talks of modifying existing.

**Comment by sebgoa** [comment]
Can you put the link to the page you are talking about ? thanks

**Comment by abrennan89** [comment]
@blorette please provide a link to the page you're referring to, or let me know if it's OK to close this issue.
Thanks.

**Comment by blorette** [comment]
@abrennan89 

Sorry, thought the report linked it. 

Its from:
https://knative.dev/docs/serving/deploying/private-registry/

If I remember correctly, setting up the ability to use a private repo. The 2nd step modifies an existing service account, and then step 3 is sort of just there.

**Comment by evankanderson** [comment]
Step 3 doesn't really make sense, because it talks about `kubectl apply`ing a file, but everything up to that point has been live-updating the service.

Removed it, and simplified the nested numbering for what is now a single step. (It was two steps, run `kubectl edit` and then change the contents in your editor.)
