### ISSUE TITLE
Knative Kubernetes Services (docs/serving/knative-kubernetes-services.md) needs improvement

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#2563]
This documentation is confusing
https://knative.dev/docs/serving/knative-kubernetes-services/

It currently describes both services and deployments, even though it's titled _Knative Kubernetes Services_.

I think that both deployments and services should probably be moved to https://knative.dev/docs/serving/ as sub sections, since the other parts of Serving are explained there.

I also think that these components need to be explained more clearly, and the missing descriptions need to be added for some deployments that are shown in the examples but not documented.

**Comment by mpetason** [comment]
I think this could be renamed Knative Kubernetes Resources since it is describing the resources running instead of what we would think of as a Service keyword in K8s. 

There's even another section of the docs that goes into Knative Services - https://knative.dev/docs/serving/services/ , which can add more confusion.
