### ISSUE TITLE
Installing Knative(docs/install/any-kubernetes-cluster.md)

### ISSUE THREAD

**Issue by josiemundi** [knative/docs#2580]
## Expected Behavior
When I run the command to install a broker layer in the installation doc 'Installing Knative', for Knative eventing I am expecting it to install the specified yaml. 

## Actual Behavior
The command doesn't work because that file does not exist. The files are now either ```mt-channel-broker.yaml``` or ```deprecated-channel-broker.yaml```.

## Steps to Reproduce the Problem

1. Go to step 4 for installing Knative eventing; 'Install a broker (eventing) layer'
2. Try to run ```kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.15.0/channel-broker.yaml```

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): 
 - Knative Version: 0.15.0

**Comment by mpetason** [comment]
@grantr @lionelvillard which files should replace the old files? 

https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-eventing-component

Step 4 both tabs

Since mt-channel-broker.yaml is the new default should it be used for both, or should we remove one of the tabs and just have the default? Or should we use deprecated-channel-broker.yaml for the first tab and mt-channel-broker.yaml for the second?

**Comment by pierDipi** [comment]
This seems to be fixed. The page https://knative.dev/development/install/any-kubernetes-cluster/#installing-the-eventing-component has only the `MT-Channel-Based` tab that uses `mt-channel-broker.yaml`. 
Also, we're removing `deprecated-channel-broker.yaml`, see https://github.com/knative/eventing/issues/3732.

/close

Feel free to reopen if there is something left out.
