### ISSUE TITLE
Install Knative Eventing missing optional upgrade step

### ISSUE THREAD

**Issue by n3wscott** [knative/docs#2622]
## Expected Behavior

There is no doc that points to run:

```shell
kubectl apply -f https://github.com/knative/eventing/releases/download/v0.14.0/upgrade-to-v0.14.0.yaml
```

Which was in https://github.com/knative/eventing/pull/3247/files

Relates to v0.15 Eventing

**Comment by abrennan89** [comment]
Should this be in the install docs or does it actually need to be updated here? https://knative.dev/v0.15-docs/install/upgrade-installation/#performing-the-upgrade

Still an issue either way. The docs here talk about upgrading to 0.13 which doesn't seem right?
Same problem:
- https://knative.dev/v0.14-docs/install/upgrade-installation/#performing-the-upgrade -> should be 0,14?
- https://knative.dev/v0.15-docs/install/upgrade-installation/#performing-the-upgrade -> should be 0.15?
- https://knative.dev/v0.17-docs/install/upgrade-installation/#performing-the-upgrade -> should be 0.17

Weirdly enough just 0.16 seems like it was updated.
Otherwise to prevent future maintenance we could maybe change this to `latest` or something, or add `<version>` instead so the document is generic and the user can sub in the right info for them? Wdyt @n3wscott ?

**Comment by vaikas** [comment]
We unified the installing / documents and point to that generic upgrade, so some cleanup there would be beneficial to everything. Latest thinking has been that we should not have a 'pre' and 'post' steps, but rather have the upgrade step, then only the post install steps. But until that lands, I do wonder if for older versions, we might want to point to applicable release notes where we linked what jobs need to run.

**Comment by lberk** [comment]
@abrennan89 based on the comments from @vaikas I think we can close this issue

**Comment by abrennan89** [comment]
Since this relates to 0.15 which is no longer live on the docs site, I think it's OK to close.

@vaikas could you please maybe raise a separate issue and/or PR re adding the links to the release notes for each docs version if this is something that is important to have?
RE "until that lands", do you mean until the changes in docs land? If there's an issue open tracking the requests to clean up and restructure docs, can you link it, and if not can you raise one please outlining the details so we can track that work?

**Comment by vaikas** [comment]
Yes, the change landed awhile ago. It was related to the fact that we had separate places where the installation instructions had diverged, so now they were pointed to a single location. As far as release notes being linked to, yes, I'll create an issue for it.
