### ISSUE TITLE
The channel-broker.yaml doesn't exist anymore but it still reported in the documentation of 0.15.x

### ISSUE THREAD

**Issue by oscerd** [knative/docs#2675]
## Expected Behavior
Being able to install a broker (eventing) layer with 0.15.0, 0.15.1, 0.15.2 and 0.15.3

## Actual Behavior
kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.15.0/channel-broker.yaml fails because it doesn't exists anymore, there is only the deprecated-channel-broker.yaml

## Steps to Reproduce the Problem

1. kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.15.0/channel-broker.yaml

## Additional Info
**Additional context**
Nothing.

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): all
 - Knative Version: 0.15.0, 0.15.1, 0.15.2 and 0.15.3

**Comment by abrennan89** [comment]
I believe that this is due to the default broker now being the multitenant broker. The old `default` broker is deprecated and will be removed entirely in a future release afaik, hence the name change of the yaml I guess.
I will update the docs to make the broker options clearer for each version and to highlight this being deprecated. I am already working on the broker story overall so this should fit into that.
Thanks for reporting, @oscerd :+1:

**Comment by abrennan89** [comment]
@oscerd could you provide a link to where you can see this command
```
kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.15.0/channel-broker.yaml
```
in the documentation? Thanks.

**Comment by oscerd** [comment]
The PR related to this has been merged I guess.
