### ISSUE TITLE
Access KNative Service locally with minikube

### ISSUE THREAD

**Issue by miguelvr** [knative/docs#2678]
Hi,

I'm trying to spin up my first KNative service, and I've been following the instructions but to no success so far.

It's not really clear how a user can access a KNative Service without exposing it through DNS. 

In a nutshell, I launched a KService, it has it's status ready and I want to verify everything is working by accessing the server webpage through the browser or curl it.

I'm using Istio, and my `istio-ingressgateway` does not have an external IP. I'm not sure why this is the case, however. 
Is there a way to access the service with, `kubectl proxy`, for example?

For context:

`kubectl get ksvc`
```
NAME                         TYPE           CLUSTER-IP       EXTERNAL-IP                                            PORT(S)                             AGE
director-api                 ExternalName   <none>           cluster-local-gateway.istio-system.svc.cluster.local   <none>                              21m
director-api-scc7b           ClusterIP      10.110.217.172   <none>                                                 80/TCP                              21m
director-api-scc7b-private   ClusterIP      10.101.107.52    <none>                                                 80/TCP,9090/TCP,9091/TCP,8022/TCP   21m
```

`kubectl get svc istio-ingressgateway -n istio-system`
```
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                                      AGE
istio-ingressgateway   LoadBalancer   10.109.86.54   <pending>     15021:31750/TCP,80:32262/TCP,443:32494/TCP,15443:30030/TCP   39m
```

**Comment by nak3** [comment]
Hi @miguelvr using NodePort for the ingressgateway does not work?
We have similar report here https://github.com/knative/net-istio/issues/168. So it would great if you could try it and let us know your feedback in https://github.com/knative/net-istio/issues/168.

**Comment by miguelvr** [comment]
Hi @nak3 

I've actually just managed to solve the problem. 

Here is how:

1. Run `minikube tunnel` in a separate terminal window
2. Add the ingress gateway IP and my service DNS address to `/etc/hosts`
```
SERVICE_NAME="my-service"

export GATEWAY_IP=`kubectl get svc istio-ingressgateway --namespace istio-system --output jsonpath="{.status.loadBalancer.ingress[*]['ip']}"`

export DOMAIN_NAME=`kubectl get route ${SERVICE_NAME} --output jsonpath="{.status.url}" | cut -d'/' -f 3`

echo -e "$GATEWAY_IP\t$DOMAIN_NAME" | sudo tee -a /etc/hosts
```
3. You can now curl the service at the DNS address

I guess these instructions, could be highlighted somewhere for the particular use-case of minikube

**Comment by abrennan89** [comment]
@miguelvr we do not document Knative for specific vendors besides allowing links to third party docs, so there are no minikube specific docs anymore.
Closing issue.

**Comment by manuelstein** [comment]
@abrennan89 I'm not sure I understand your response, could you maybe help understand the details if you don't mind?

> we do not document Knative for specific vendors besides allowing links to third party docs

I understand Minikube is under the umbrella of K8s (github.com/kubernetes/minikube) and contributions go to the CNCF.
Knative serving, like all Knative, is under the Google CLA.

I also noticed some documentation specific to providers, e.g. 
https://knative.dev/docs/serving/using-cert-manager-on-gcp/
https://knative.dev/docs/serving/gke-assigning-static-ip-address/
which are specific to Google.

I'm not even mad, the more documentation the better. And I know it's a pain to maintain so documentation for so many setups (kubespray, minikube, kubeadm, k3s, younameit).

So, when you say "specific vendors", do you mean other than Google?

@miguelvr, IIUC the solution you're mentioning adds the Route's status.url to /etc/hosts and although I know that works, I think there are some flaws here.

The service cluster-local-gateway could be redeployed and get a new cluster ip in which case your /etc/hosts will not be synched. Also, you have to update /etc/hosts for every service that you are going to deploy.
But actually what should happen is, that anything outside your kubernetes networking (e.g. not in a pod), should use the ingress gateway. I see you have deployed istio-ingressgateway, but AFAICS it's not getting a LoadBalancer IP address. That's why @nak3  asked for the NodePort type.

Personally, I don't like the NodePort solution either, because it requires to set a separate Host header in HTTP requests without the trailing port.

Consider using the IstioOperator with the following config to change the type of the Service ingress-gateway to ClusterIP:
`apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: ClusterIP`

This will create the Service istio-ingressgateway with type ClusterIP and not wait to get a LoadBalancer external IP address.
(Be sure to undeploy the Service first, because istioctl won't be able to update it and change its type from LoadBalancer to ClusterIP).

Second, your kservice needs to actually become externally accessible (I mean not punching requests from outside into the cluster-local-gateway). You can configure knative serving to use the xip.io domain (see https://knative.dev/v0.15-docs/install/any-kubernetes-cluster/ Magi xip.io DNS). So, e.g. your ingressgw has clusterIP 10.109.86.54, then your domain name will be 10.109.86.54.xip.io and your services will actually be bound to director-api.yournamespace.10.109.86.54.xip.io and you can access them without hacking /etc/hosts.

Best, Manuel
