### ISSUE TITLE
Distill Knative install steps into a shareable set

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#270]
## Expected Behavior
Have a single set of Knative specific install steps that all hosts can use/point to instead of duplicating those same steps throughout each install guide.

## Actual Behavior
All the various host install instructions copy the section that cover the Knative install steps
(https://github.com/knative/docs/tree/master/install).

**Comment by RichieEscarez** [comment]
From #265: "Installing serving also installs build"

Therefore, the instructions for installing Knative components should be revised to clarify that you can install both "serving and build" or "build only".

**Comment by samodell** [comment]
I started working through the changes necessary for this, but I think it ultimately leads to a super fragmented experience, where we'd be asking users to visit multiple pages to complete their install. I think the current state of affairs is probably preferable, so I'm going to close this out. I'll leave my WIP PR open for now, in case anyone disagrees strongly.

**Comment by krancour** [comment]
I agree that it's better as is because the install instructions do vary in some cases. For instance, on minikube, the "lite" release is installed due to resource constraints and services of type `LoadBalancer` are exchanged for services of type `NodePort`. Accounting for things like that in one, unified install doc would mean logical if/else forks in the doc and that is a harder doc to follow because you cannot mindlessly copy/paste step after step. You'd have to scrutinize every step of the way to make sure you wete doing the right thing.
