### ISSUE TITLE
Add troubleshooting information to contributor docs

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#2755]
Our current [contribution docs](https://knative.dev/community/contributing/docs/docs-contributing/#submitting-documentation-prs---what-to-expect) don't provide information about what to do if:

- the CLA fails because you accept and commit suggestions from someone else
- any of the automatic tests that run on PRs fail
- previews don't work (seems to be often now)
- you're not sure which version your changes need to be cherrypicked to (not a blocker, but I feel like guidance about things being cherrypicked generally would be nice if we don't have it)

**Comment by RichieEscarez** [comment]
Some info to help unblock people: 

*- the CLA fails because you accept and commit suggestions from someone else*

GitHub commits are connected to each author and Knative contributors must sign a [CLA](https://knative.dev/community/contributing/contributing/#contributor-license-agreements).

*- any of the automatic tests that run on PRs fail*

Which tests? Looks like there are lots now that those owner would be able to help explain? 

Link checker: I believe this is the link checker that was initially set up (picked because its OSS and actively supported): https://github.com/raviqqe/liche (https://github.com/knative/docs/pull/1954), which is unable to distinguish URLs in content vs those within comments in the file (thus will find a broken link if the URL in the comment is bad).

*- previews don't work (seems to be often now)*

The Netlify PR builds output here: https://app.netlify.com/sites/knative/deploys
This work is incomplete. You must search the build log for the PR number. Right now all changes to any PR gets built here (but there is not a mechanism to send that back to the individual PRs). The script also assumes that the branch name is `docs` (ie. myforkname/docs).

*- you're not sure which version your changes need to be cherrypicked to (not a blocker, but I feel like guidance about things being cherrypicked generally would be nice if we don't have it)*

I think thats covered here: https://knative.dev/community/contributing/docs/docs-contributing/#choosing-the-correct-branch
