### ISSUE TITLE
Feature state labels are unclear in certain contexts (we should change '@' to 'since')

### ISSUE THREAD

**Issue by julz** [knative/docs#2781]
## Expected Behavior

1. On pages such as https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-serving-component, the Serving link should not be suffixed by "stable @ v0.9" in the opening paragraph, because to at least one reader (hi! 👋) this looks like we're suggesting the current stable version is 0.9.
1. It's fine to have "stable @ v0.9" when this is preceded by "Feature State:" since this makes it clear what the '@' means, but:
1. Even better (imo) would be just to use "stable since v0.9" throughout, since this is clear in all contexts

## Actual Behavior

1. The opposite of the above.

## Steps to Reproduce the Problem

1. Visit https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-serving-component
1. Read the opening paragraph
1. Observe "Serving `stable @ v0.9` provides an abstraction for stateless request-based scale-to-zero services." rather than something like "Serving `stable since v0.9` provides an abstraction for stateless request-based scale-to-zero services."
1. Repeat throughout docs.

/assign @abrennan89

**Comment by rhuss** [comment]
Totally agree, but tbh I question in general to show this information in introductory documents like the installation guide. See #2858 because I got confused about this information. My feeling is that nobody really cares that Knative is stable since 0.9.0 (considering we are already at 0.17) or whether it was in 0.8.0 or 0.10.0. All those versions are not supported anymore anyway. 

I would just remove those labels.

**Comment by csantanapr** [comment]
+1 to remove the labels from intro and installation docs.
I also always confuse about what does this `@` means and also think I'm looking at a very old version of the docs installing old versions.
