### ISSUE TITLE
Add a FAQ section

### ISSUE THREAD

**Issue by rhuss** [knative/docs#2809]
## Describe the feature:

A FAQ should shortly describe how to realize common use cases with a single command. Actually we could borrow some ideas of https://knative.tips and show how those tips could be implemented via `kn` (as it looks like that the ghost behind knative.tips is not very positive to include `kn` on that web site). But other FAQs are equally well suited. Ideally, each FAQ shows a single kn illustrating a certain use case.

This is part of knative/client#510

**Comment by abrennan89** [comment]
I'm not really sure what the use case for an FAQ would be that wouldn't be covered either by user docs, reference docs, or adding troubleshooting info when documenting the commands? Also, I'm not really a fan of things like FAQ docs because you have no idea going in whether the thing you're looking for is actually documented there.

**Comment by rhuss** [comment]
The original idea was to include the `knative.tips` content without much changing it. As the content is in a kind of FAQ like style, I thought that would be the easiest way to consume that content.

However, since knative.tips is dead since quite some long time, this is not relevant anymore as knative.tips is very likely outdated these days (also we don't have access to the source code anyway). 

from mys side we can close this issue.
