### ISSUE TITLE
Update SinkBinding docs to use v1

### ISSUE THREAD

**Issue by capri-xiyue** [knative/docs#2917]
## What is changing? (Please include as many details as possible.)
In 0.19, we are promoting SinkBindingto v1.
We should update the docs accordingly.

## How will this impact our users?
They will be able to start using SinkBinding in v1

## In what release will this take happen (to the best of your knowledge)?
0.19

## Context
Link to associated PRs or issues from other repos here.

1. knative/eventing#4176, which has all the PRs linked to.

**Comment by abrennan89** [comment]
#### Notes:
Issue that added sink binding docs: https://github.com/knative/docs/issues/2492

It seems like now there are 2 different places for sink binding docs:
- https://knative.dev/docs/eventing/samples/sinkbinding/
- https://knative.dev/docs/eventing/sources/sinkbinding/

I think the issue was closed because it was stale, but to me it looks like there's work to do here to combine them into one doc and clean it up. I went to reopen that one but I'll just do that as part of this issue instead.

/assign

**Comment by capri-xiyue** [comment]
> #### Notes:
> Issue that added sink binding docs: #2492
> 
> It seems like now there are 2 different places for sink binding docs:
> 
> * https://knative.dev/docs/eventing/samples/sinkbinding/
> * https://knative.dev/docs/eventing/sources/sinkbinding/
> 
> I think the issue was closed because it was stale, but to me it looks like there's work to do here to combine them into one doc and clean it up. I went to reopen that one but I'll just do that as part of this issue instead.
> 
> /assign

I think https://knative.dev/docs/eventing/samples lists all the code samples that knative-eventing, knative-gcp, eventing-contrib supports.
but https://knative.dev/docs/eventing/sources just lists the sources that knative-eventing supports.
If we combine them into one doc, it may look confusing here because it doesn't match the inherent logic of the documentation.
