### ISSUE TITLE
Add docs for GitLabBinding

### ISSUE THREAD

**Issue by pianohacker** [knative/docs#3111]
**Describe the change you'd like to see**
The GitLabBinding allows for GitLab credentials to be stored in one place then referenced by multiple deployments or sources. It's currently not documented at all.

**Additional context**
https://knative.slack.com/archives/C9JP909F0/p1608241376321800

**Comment by vaikas** [comment]
@antoineco is this something that you might be able to take a look at?

**Comment by antoineco** [comment]
I'm not even sure whether this was ever properly tested, so I would be careful documenting it 🙂 @pianohacker do you have any experience using that?

For the context, @mattmoor requested that every (?) source has a corresponding "binding" some time ago. The goal was not to allow multiple sources to reference the same credentials (we can already do that with Kubernetes Secrets), but rather to let the binding decide about the best way to provide credentials to the consumer.

For example, if the GitLab client was to expect credentials to be read from a _file_ in a standard location (like [AWS SDKs](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#hdr-Sessions_options_from_Shared_Config) read credentials from `~/.aws/credentials` by default, for example), the binding could do that instead of passing those credentials via environment variables. To my knowledge, the GitLab client doesn't have such default, so we never really put the effort into creating a proper Binding object, knowing that it required another reconciler, etc.

**Comment by abrennan89** [comment]
Closing this issue for now until we have some confirmation from @knative/eventing-wg-leads that this should actually be documented. Doesn't look like this is a decision docs can make atm.
