### ISSUE TITLE
Hello World - Python(docs/serving/samples/hello-world/helloworld-python/index.md)

### ISSUE THREAD

**Issue by ominiet** [knative/docs#3371]
## Expected Behavior
Clicking Link to installation instructions to send to installation instruction docs

## Actual Behavior
link navigates to 404 page

## Steps to Reproduce the Problem

1. start on https://knative.dev/docs/serving/samples/hello-world/helloworld-python/index.html#prerequisites
1. click _installation instructions_ link
1. be redirected to https://knative.dev/install/index.html instead of https://knative.dev/docs/install/

**Comment by mpetason** [comment]
Looks like these pages have the same issue:

https://knative.dev/docs/serving/samples/hello-world/helloworld-go/#prerequisites
https://knative.dev/docs/serving/samples/hello-world/helloworld-java-spark/#prerequisites
https://knative.dev/docs/serving/samples/hello-world/helloworld-java-spring/#prerequisites
https://knative.dev/docs/serving/samples/hello-world/helloworld-shell/#prerequisites

**Comment by evankanderson** [comment]
I think this is a bug in the website build script here:

https://github.com/knative/website/blob/main/scripts/processsourcefiles.sh#L146

You can experiment with the website build statically to figure out what's going on: https://github.com/knative/website/blob/main/DEVELOPMENT.md

I might be able to take a look later this week, but we should be moving to `index.md` or `_index.md` files, and away from the `README.md` files with an include bit, since the include breaks nested shortcodes like `{{tabs}}`.
