### ISSUE TITLE
Serving API links are broken

### ISSUE THREAD

**Issue by benmoss** [knative/docs#3405]
The links on https://knative.dev/docs/serving/ to Service, Route, Configuration and Revision are broken.

They are linking to URLs like https://knative.dev/blob/master/docs/serving/spec/knative-api-specification-1.0#service instead of https://knative.dev/docs/serving/spec/knative-api-specification-1.0#service

As a side-note, the 404 page that is shown when you follow those also is lacking CSS.

**Comment by evankanderson** [comment]
Oof, these got moved to https://github.com/knative/specs/blob/main/specs/serving/knative-api-specification-1.0.md, but it would be nice to extract the high-level descriptions and get them back on the website.

/assign @tayarani 

/good-first-issue

**Comment by tayarani** [comment]
@evankanderson would it be bad if they links pointed to the specs repo? Instead of duplicating parts of the docs in serving.

**Comment by evankanderson** [comment]
(sorry for the delay, got caught up in release/automation work)

**Comment by pmbanugo** [comment]
Just adding to this because the links captured in the screenshot below also have failing links, and the 404 page looks like there are no styles for the page and everything is in disarray. 

<img width="731" alt="Screenshot 2021-04-26 at 17 17 19" src="https://user-images.githubusercontent.com/4036118/116107671-85423e80-a6b3-11eb-952f-15d2d8635db5.png">

**Comment by abrennan89** [comment]
@tayarani any update on this issue?

**Comment by evankanderson** [comment]
These links don't seem to be broken anymore, though they jump through an interstitial page we should probably remove at some point.

/close
