### ISSUE TITLE
[Investigation Needed] "Edit Page" button doesn't work

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3733]
## Expected Behavior
When I click on the Pencil Icon 
![Screen Shot 2021-06-04 at 5 23 39 PM](https://user-images.githubusercontent.com/16281246/120864071-a111ed80-c559-11eb-9079-87c0dee508a1.png)
I see the page I am viewing on Github

## Actual Behavior
Broken link 

## Steps to Reproduce the Problem

1. Load any page that isn't the homepage
2. Click the pencil
3. Read it and weep

## Additional Info
This might be fixed when `mkdocs` is `main` but I want to be sure

**Comment by julz** [comment]
Yep, this is currently set to use `main` rather than `mkdocs` branch here: https://github.com/knative/docs/blob/mkdocs/mkdocs.yml#L8. We could swap that to be `edit/mkdocs/docs` instead, but we'll just have to switch it back after 🤷. 

If you want to validate you can just swap that locally and run mkdocs serve, or push a WIP commit with that changed.

**Comment by csantanapr** [comment]
This means we are renaming mkdocs branch to main ?

**Comment by julz** [comment]
replicating some context from a long slack thread here: we _will_ rename, but not till after go-live (since we will be building the _old_ site from main till then), so we probably do want to fix this before go-live (and then un-fix it after! :))

**Comment by omerbensaadon** [comment]
added priority and milestone :D
