### ISSUE TITLE
"Contribute" button in Homepage footer is broken

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3752]
## Expected Behavior
The "Contribute" button takes you to the contributor gude

## Actual Behavior
It's a broken link

## Steps to Reproduce the Problem

1. Go to homepage
1. Scroll down to the bottom of the page
1. Click "Contribute" 

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by abrennan89** [comment]
If we're talking about this one 
![image](https://user-images.githubusercontent.com/40172997/122260023-6df42600-ce98-11eb-9c37-9fee7272bfff.png)

It seems to work fine for me and brings me to https://dev-knative.netlify.app/development/help/contributor/, so I guess this was fixed in the meantime? Closing the issue.
