### ISSUE TITLE
ksvc alias doesn't work with knative v0.1.1 as described

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#379]
## Expected Behavior

https://github.com/knative/docs/blob/eab66f7c86bb1b6c0ee570094565c9b081f5a4d2/serving/samples/helloworld-go/README.md says:

> Note: ksvc is an alias for services.serving.knative.dev. If you have an older version (version 0.1.0) of Knative installed, you'll need to use the long name until you upgrade to version 0.1.1 or higher.

## Actual Behavior

```
kubectl get ksvc helloworld-go  -o=custom-columns=NAME:.metadata.name,DOMAIN:.status.domain

error: the server doesn't have a resource type "ksvc"
```

even though knative 0.1.1 was installed in the first place.

## Steps to Reproduce the Problem

1. Install knative v0.1.1 to GKE [from this doc](https://github.com/knative/docs/blob/eab66f7c86bb1b6c0ee570094565c9b081f5a4d2/install/Knative-with-GKE.md#whats-next)
2. `kubectl get ksvc helloworld-go  -o=custom-columns=NAME:.metadata.name,DOMAIN:.status.domain` 
3. Get error.

**Comment by RichieEscarez** [comment]
in all docs we do mention "*ksvc is an alias for services.serving.knative.dev*" so not P0 but `ksvc` is not working right now

**Comment by steren** [comment]
`ksvc` has been introduced in https://github.com/knative/serving/pull/1723
If it does not work, please open this issue on the https://github.com/knative/serving repo

**Comment by ahmetb** [comment]
Opened https://github.com/knative/serving/issues/1995 to track API issue.

I recommend removing this from the documentation for now until this works.

The abbreviated form simply isn't there in `kubectl api-resources`. I suspect either the commit didn't make it to the release or some other issue.

**Comment by ahmetb** [comment]
Just verified commit https://github.com/knative/serving/commit/401b1ba25e8187325a1ce7f6e431bc5fbf4ce8ec didn't make it to the v0.1.1 release.

**Comment by steren** [comment]
I think the underlying question here is: how to handle docs versioning? When should a feature be documented?

**Comment by ahmetb** [comment]
That's a bit off-topic but for this simple instance, release changelog should be reflecting whether the feature is in v0.1.1 or not.

Docs versioning is a non-trivial problem, kubernetes solved it in v1.8 and until then (and still) they use "this feature is in available in vX.Y or later" notices all over the place.

Unless roadmaps/changelogs are accurate, people writing the docs can't do much better.

**Comment by RichieEscarez** [comment]
The versioning topic is actively being discussed, particularly since it needs to align with what works with the Knative site (which is nonexistent because it lacks resource, both ownership and clear direction). 

Since Kubernetes v1.0, there have been snapshots/branches created in the repos, which is likely something that needs to be done for this doc set.

But, there are several questions that surround versioning, which should be answered first, including:

- how is the user experience affected when SEO starts to favor and suggest the oldest versions of a doc repo and sends all search results to the v1.0 (because the receive the most traffic for the longest)
- if we snapshot now, since we lack a significant set of content (doc gaps) and new content is actively being authored (some in PRs now), does that new content get added to all versions, or only added to HEAD/master
- how many versions of the docs should be maintained

- how to maintain several copies of the same document (maintaining copies in each branch/version)
  - is it more efficient/effective to state inline support (versus juggling multiple PRs to maintain files across multiple branches)
  - how to communicate/identify if an issue affects one version or multiple versions (issues, PRs, etc)
  - how to communicate when code changes affect only one version of the docs

- how to communicate/highlight changes per version 
  - do we create and maintain release notes
  - who manages the list of changes and provides them to the docs team

- who owns the snapshot/versioning process and when does that get done

**Comment by rgregg** [comment]
Can we split this and have this issue focus on the underlying issue, and have a separate issue that can focus on the doc versioning problem?

The install guide, which installs 0.1.1, references syntax that is not supported in 0.1.1. That's a bug we should fix as a high priority, since it means new users get a broken experience.
