### ISSUE TITLE
[DOCS SPIKE] What should we do with our sample content?

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3796]
## Description: 
We have samples under `/samples/`, `/serving/samples/`, `/eventing/samples` and `community/samples`. 

It would be nice to figure out what structure we want these to take on the Knative site before launch. 

There have also been recommendations of moving the samples outside of the Knative website altogether and into GitHub (if so, we can host it over in the UX Repo maybe?). 

This Docs [Spike](https://en.wikipedia.org/wiki/Spike_(software_development)) is to flesh out a desired state for where samples should live. 

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [ ] New Contributors

**Comment by snneji** [comment]
We already have a Code samples section in the top level navigation, so from a users point of view I think we've already made a decision (ie have serving and eventing code samples on the site and have community code samples in GitHub with a link in the docs).  

In terms of directory structure, my vote would be to have a `docs/samples/` folder containing all samples. This course of action is described in issue #4378. 

In my opinion we can close this issue in favour of #4378. 

cc: @omerbensaadon, @abrennan89 adny thoughts on this?

**Comment by abrennan89** [comment]
I think it would be better to have samples maintained as code in engineering repos and a way to point to them or include them in docs; these aren't something writers should be responsible for maintaining IMO.
I also think they would be more useful to users in the relevant sections than in one big jumble of samples, e.g. put autoscaling samples with autoscaling docs, Kafka samples with Kafka docs, broker samples with broker docs

**Comment by snneji** [comment]
@abrennan89 I agree that writers shouldn't be responsible for maintaining code. When you talk about moving the samples to be maintained as code in engineering repos, do you mean move only the code files in each [sample folder](https://github.com/knative/docs/tree/main/docs/serving/samples/cloudevents/cloudevents-dotnet)? Or do you also mean moving the procedure files such as [this example page](https://knative.dev/docs/serving/samples/cloudevents/cloudevents-dotnet/)? Should the sample procedures be only shown in GH or should they have a webpage on the Knative site?

I would like this issue to be closed soon because it has been around for a while. Since I don't think I have enough context to work out what's best alone, and I don't want this to end up being a long thread, I'm going to put this on the WG agenda for this week. If you want to add your opinion, come along to the meeting. Otherwise, put your opinions in this thread and I'll make sure they are added to the conversation.

**Comment by csantanapr** [comment]
All sample codes should be store in another git repo than docs repo 

The sample instructions markdown should not be in render in the website even is the code and md files live in another git repo other than docs repo

The code should be along side with the tutorial/instructions to run 

The location of the samples is something to discuss

One alternative is to have them in the git repos in serving and eventing. 

Or create a new git repo in Knative-sandbox name "Knative-examples"

On the website will have the sections for examples/samples have a short description of the sample and link to Github folder where the README.md will tell the user how to use the example located in the same directory

**Comment by nainaz** [comment]
+1 to @csantanapr suggestions. 
Code samples reading and access on website can be improved by have a link to Github for navigating the examples. As  developers are used to of this flow of following examples on GitHub. 
Samples can live in the docs repo on Github.

**Comment by snneji** [comment]
After discussing in the WG meeting we have decided to render the code samples in GitHub only, with links to the samples on the website.

On the subject of moving the samples to another repo, there were concerns about whether engineers would want to maintain the samples in their repos. Also, there were concerns about who would be responsible for PRs if we created a new repo. Because of this we decided to leave the code sample files in the docs repo for now.

**Comment by snneji** [comment]
> I also think they would be more useful to users in the relevant sections than in one big jumble of samples, e.g. put autoscaling samples with autoscaling docs, Kafka samples with Kafka docs, broker samples with broker docs

The code samples section was created according to the consensus view from the card sort. I think it's nice to have a central location where users can look up all code samples. Serving has a [table](https://knative.dev/docs/serving/samples/) organizing the samaples, Eventing should have one too. 

If we like we can link from docs such as autoscaling to where users can find relevant samples.
