### ISSUE TITLE
Broken link - Knative Eventing(docs/eventing/_index.md)

### ISSUE THREAD

**Issue by jai** [knative/docs#3831]
## Actual Behavior

Link to 'trigger' documentation is broken.

## Steps to Reproduce the Problem

1. Visit https://knative.dev/docs/eventing/
1. Click on "trigger" under Functionality bullet-item-2
1. See 404

**Comment by abrennan89** [comment]
The information in the description of this issue doesn't seem correct.

I think you're referring to: https://dev-knative.netlify.app/development/serving/samples/hello-world/helloworld-csharp/ ?
In future issues, @jai please just add a direct link to the page you're referring to.
There doesn't seem to be any csharp / .NET sample for eventing https://knative.dev/docs/eventing/samples/helloworld/

None of the links on this page appear to be broken to me, but I don't see any link for triggers here either, so I'm really not sure what this refers to.

**Comment by abrennan89** [comment]
lol please don't use numbers like `#2` n issues - I spent a good 5 minutes looking in the C# sharp sample for a broken link because it added the link to the PR for that sample (see above) 😂 
You can ignore the previous comment I added / deleted @jai 🙃 

This link is fixed in the latest version of the docs: https://dev-knative.netlify.app/development/eventing/
I'm not sure if we plan to keep maintaining the older versions @julz @omerbensaadon or should we close this issue?

**Comment by jai** [comment]
Sorry about that @abrennan89 I totally should have seen that auto-link!

**Comment by abrennan89** [comment]
@jai it's all good 😄

**Comment by omerbensaadon** [comment]
If this is fixed in pre-release, we can close this issue! 

Thanks @jai @abrennan89
