### ISSUE TITLE
Add automation to comment in "snippets" location anywhere a snippet is used

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3878]
**Describe the change you'd like to see**
It is confusing for new contributors to not understand where snippets are coming from (see #3871), and it's a bit too much overhead to ask all docs writers to include comments with every snippet. 

It would be nice to add to our Github Actions a comment above any snippet which reads: 

```
// Below is a "snippet" which is a tool we use for content-reuse. It can be found in: docs/snippets. For more information on how to use snippets see docs/snippets/README.md
``` 

**Additional context**

**Comment by abrennan89** [comment]
I personally don't think it's that much overhead to just manually add this; I think we just need proper contrib docs about specifically how to use snippets for our docs, and this note could be added there to copy/paste.
WDYT @snneji @RichardJJG ?

**Comment by RichardJJG** [comment]
> I personally don't think it's that much overhead to just manually add this; I think we just need proper contrib docs about specifically how to use snippets for our docs, and this note could be added there to copy/paste.
> WDYT @snneji @RichardJJG ?

I think for the GitHub Action to be worthwhile it would need to be very clever about always using correct indentation, not overwriting text, etc, etc, and also seldom (or never) require updating. If such a GitHub Action can be super clever and also require next to zero technical overhead forever, I would prefer it over manually adding that note.
 
Otherwise I think we have to just manually add the text as, long-term, it would probably be the less onerous option.
