### ISSUE TITLE
Statefulset can also support autoscale after Kuberntes 1.9

### ISSUE THREAD

**Issue by gyliu513** [knative/docs#3941]
Kuberntes 1.9 do support scaling Statefulset https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ , so with issue comment https://github.com/knative/docs/issues/3841#issuecomment-867790502 , can we remove the `stateless` requirement?

But still, I think the Kuberntes Statefulset does not support scale to 0, but should support scale from 1 to N.

@evankanderson comments?

**Comment by evankanderson** [comment]
Knative assumes that the workloads are stateless; it uses a Deployment under the covers, and may remove Pods at random rather than assigning indexes and removing the last index.

For workloads which are amenable to Knative's workload management, it can simplify one common case for Deployments (12-factor HTTP applications). Not all Deployments are suitable for Knative workload management (as an example, Rook uses Deployments with host constraints to manage OSDs), but StatefulSets almost certainly are not.

**Comment by evankanderson** [comment]
To put this another way, even if Kubernetes supports managing and scaling a workload, it may not be suitable for Knative. That's by design; you can always use Kubernetes to manage the workload, and Knative aims to simply one pattern by making assumptions about the workload that rule out other (reasonable, supported by Kubernetes) workloads.

**Comment by gyliu513** [comment]
Thanks @evankanderson , very clear.

BTW: Does Knative has any plan to support Stateful resources other than Stateless?

**Comment by evankanderson** [comment]
Eventing components tend to be stateful, but it seems unlikely that Serving will provide support for stateful applications.

To misquote Leo Tolstoy:

> 12 factor applications are all alike, every stateful application mangages state in it's own way.

While this may not strictly be true, the range of state assignment and handover needs between applications varies widely. I'd be excited to see similar toolkits for common stateful application patterns (e.g. https://agones.dev/ for gamedev), but I don't think the Knative community has aspirations there.

**Comment by gyliu513** [comment]
@evankanderson sorry for late response, I want to had more discussion about this: considering the k8s already support scaling statefulset, can the knative be enhanced just align with k8s? Do not need to scale statefulset to 0, but just scale it between 1 and N, does this make sense?
