### ISSUE TITLE
Local build (`mkdocs serve`) doesn't work with out of date mkdocs version

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3946]
## Expected Behavior
When I run `mkdocs serve` it renders the site locally

## Actual Behavior
It shows me the error: 
```
INFO    -  Building documentation... 
WARNING -  Config value: 'INHERIT'. Warning: Unrecognised configuration name: INHERIT 
ERROR   -  Config value: 'plugins'. Error: Invalid Plugins configuration. Expected a list of plugins 
Aborted with 1 Configuration Errors!
```

## Steps to Reproduce the Problem

1. Pull latest commits (this bug impacts everything after #3797 was closed) 
1. Do mkdocs serve
1. Read it and weep 

## Additional Info
**Additional context**
This is fixed by doing 
```
pip install --upgrade mkdocs-material
pip install --upgrade mkdocs
```
and needs to be documented somewhere in the contributor's guide.

**Comment by snneji** [comment]
Might be useful to add a troubleshooting section or page and add these instructions there.

**Comment by omerbensaadon** [comment]
Yeah we may want to put this as part of the contributor's guide or something? 

Or an MkDocs FAQ of some kind?

**Comment by julz** [comment]
Possibly controversial opinion: we don't actually need to do much here or add a troubleshooting section. There are two sets of people - those already using mkdocs on the project who might have an old version, and new people going through the contributor guide for the first time. 

The first set have already fixed this for themselves since we told everyone on slack etc and I think we're pretty confident tbh everyone in this set is ok now. 

To fix the second I think all we need to do is make the instruction in the contributor guide say something like `pip install "mkdocs>=1.2"`. Then anyone following the guide will definitely have an acceptable version.

**Comment by snneji** [comment]
@julz do you think that we might want to upgrade mkdocs again in the future? If so, it might be useful to have this info somewhere that people can access it. If not, we can apply your suggestion.

**Comment by abrennan89** [comment]
@julz @snneji is there any action required here or can we close this one?

**Comment by julz** [comment]
I think I'd vote we close for now. Anyone getting mkdocs now will have an acceptable version. If we need to help folks upgrade mkdocs in the future we can add some instructions then (I'd hope it will be a while before that, though).
