### ISSUE TITLE
„Home“ button missing

### ISSUE THREAD

**Issue by embano1** [knative/docs#3976]
**Describe the change you'd like to see**
Once I‘m in a section, e.g. click „Cluster Administrator?…“, I cannot easily go back to the front matter. I have to go through the side bar menu, clicking several times on the „back“ button until I can click on „Knative“ which brings me back home. A workaround for now is to click on the version drop-down, which is not very intuitive. 

Solution: I can click on „Knative“ in the top bar or the „Home“ button is always rendered in the side bar, which then brings me back to the front matter.

**Additional context**
n/a

**Comment by julz** [comment]
This might be worth bringing up as a feature request on [the Mkdocs-material theme repo](http://github.com/squidfunk/mkdocs-material) since ideally we'd pick up a feature from there rather than building our own here (unless there's already an upstream issue for something like this already obviously).

**Comment by embano1** [comment]
I just realized that the logo to link back to the homepage is actually there in desktop mode but not shown on certain screen sizes (phone). 

![image](https://user-images.githubusercontent.com/15986659/125593535-5bb192fa-af15-4f95-ae70-3e51381e5b01.png)

Not sure if this is configurable for the mobile theme though?
