### ISSUE TITLE
We need a way to report security issues

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#401]
I'd recommend that we create something like `knative-security` that is world reportable, but very tightly readable.

**Comment by mchmarny** [comment]
@mattmoor is that a `knative-security` mailing list or project/issue list? Trying to decode the `world reportable, but very tightly readable` part

**Comment by mattmoor** [comment]
I think we probably want a distribution list

**Comment by mchmarny** [comment]
OK, I'll work with Evan on this. Do we need a separate doc `knative/docs` on this or some additional text to clarify the types of issues one should send in there? 

/unassign @mchmarny 
/assign @evankanderson

**Comment by RichieEscarez** [comment]
sgtm, we'll use that verbatim =). Sam offered to take this on since she's in the process of updating our templates. 

We chatted about adding something in our issue template and also moving all our existing troubleshooting info into a standalone file and then linking `knative-security@googlegroups.com` from there too.
