### ISSUE TITLE
Add a 'Books, courses, and videos' section in the documents

### ISSUE THREAD

**Issue by salaboy** [knative/docs#4085]
There is a free full book from Manning about Knative in Action. This should be added front page of the website so new users are aware that there is a book available and it is free to download. 

**Describe the change you'd like to see**
I wanna know and see the book when I first enter the knative.dev website.

**Additional context**
Links in the docs about other books mentioning Knative should be added

**Comment by julz** [comment]
Looks like the book is [not free](https://www.manning.com/books/knative-in-action) unless you [give your email to VMware](https://tanzu.vmware.com/content/ebooks/knative-in-action) so I'm not sure whether linking to the free version is "right" on the community site or not (though it's a great book and a great thing that VMware is sponsoring it!). Maybe this is something steering should weigh in on.

**Comment by salaboy** [comment]
@julz we might separate this into two things then.. 
- Showing that the book exists and promote it.. I believe this is a big thing for Open Source projects, to show that a big editorial has a published book. 
- Having a link that says that it is sponsored if you want to download it.

**Comment by julz** [comment]
Ack, I'm just a little jittery, personally, about links to commercial/vendor stuff directly from the community home page. Looking at Istio and Kubernetes' websites, neither of them seem to link to a book. Rust does, but it's literally a html version included directly on the website that's both free and unsponsored.

**Comment by salaboy** [comment]
@julz let's make sure that the fact that is sponsored doesn't block people from finding a valuable resource.

**Comment by julz** [comment]
> I would promote YouTube videos, no matter which vendor is producing them

Indeed so would I (and [often do](https://twitter.com/doctor_julz/status/1251082754613182464?s=20) fwiw), but not on the front page of the community site, personally. Would we link to IBM Cloud's knative service (for example) from the front page, since it offers a free tier and is a fast way to get started, or eg TriggerMesh's [free training course](https://www.triggermesh.com/knative-eventing-training)? It feels like a slippery slope I'd personally rather us not slide down, but it's Steering's call, at the end of the day: if they were happy, I'd be happy.

Adding a "knative books and courses" page to the getting started section, similar to the knative offerings page we already have (and maybe even linking to that page from the home page) would be fine with me.

**Comment by abrennan89** [comment]
Agree with @julz here, I don't think it's a good idea to promote a vendor-sponsored resource on the main community site.

> Adding a "knative books and courses" page

+1 for that, I don't see an issue there. Let's repurpose this issue to track that instead.

**Comment by salaboy** [comment]
Let's add the topic to the Steering committee agenda so they discuss this. 
But 100% behind the idea of Books, Courses and probably videos as well.

**Comment by salaboy** [comment]
Great to see @abrennan89 also joining here!

**Comment by vaikas** [comment]
I think we should have a section like that for sure. One question is what the vetting process for getting things in there will be. I could for example foresee something like, open a PR, maybe if somebody can vounch for it, they stamp it, if we don't have that, perhaps somebody should be assigned to check it out before adding?
Regardless, I added to SC agenda for this weeks meeting.
Thanks all!

**Comment by vaikas** [comment]
Let's do this! @pmorie @vaikas will be on point from SC to make forward progress.

**Comment by pmorie** [comment]
i'm supportive of making this available for download, great opportunity to help folks learn and spread the project around.

**Comment by pmorie** [comment]
hrm i wonder if we can avoid the need to hand out one's email

**Comment by vaikas** [comment]
I think the proposed plan is to:
 * Create a new section in the documents "Books, courses, and videos" (or sumtin like that)
 * Add things there that we already know of and have been vetted. I think for something like a book that requires an email address, we could make a note of that in the link, description, etc.
 * Define a process for adding new content. Mainly I'm just wanting to make sure that we do not make it more difficult than necessary to add new content (we want it!) but want to make sure that at least folks look know what's being added.
 *

**Comment by julz** [comment]
Yeah @pmorie the email capture is the bit that made me a bit uncomfortable with it being on the home page, personally.

@vaikas that plan sounds perfect to me 👌

**Comment by pmorie** [comment]
@julz if we got the email capture removed how would you feel

**Comment by julz** [comment]
My main hesitation is the email capture so without that I'd personally be a lot more comfortable with it (we'd still be linking to only one specific vendor's product-branded page from the home page; how much - if at all - we should care about that Id defer entirely to y'all on steering though 😊)

I think @vaikas's approach of having a generic resources page with a clear policy for how stuff gets added, is quite a nice solution without a lot of downsides (it's also easier to add and remove links to a markdown page than to modify the html homepage).

**Comment by salaboy** [comment]
I am super happy to see this moving forward, happy to help as well.  I am 100% agree with @julz and @vaikas proposal

**Comment by vaikas** [comment]
Started looking at this and realized we already have "Knative books" section here that already lists the book mentioned and the "Knative cookbook":
https://knative.dev/docs/getting-started/next-steps/

How do folks feel just adding "Knative courses" and "Knative videos" there? I think we might want to add a note to the "Knative in action" that states that it requires an email registration?

**Comment by omerbensaadon** [comment]
I think if we're too sensitive about playing "favorites" between vendors we will lose sight of the greater purpose for our collaboration.

We are a community of contributors most of whom happen to work for one of the major contributing vendors. Though we may sometimes have competing outcomes in the short term, **in the longterm, we all want the same thing: the Knative spec as a standard for Serverless workloads.** 

If one vendor has spent time and money creating a _free_ resource which helps people to more easily understand and adopt Knative, thus increasing our "mindshare,"  we should not shy away from linking to such a thing. [Especially not when the form used to capture emails is so easy to abuse.](https://user-images.githubusercontent.com/16281246/129582062-07992e07-2984-4f5e-bd6a-2cf85c8f4577.mov)

If, for example, RedHat (or IBM, or TM, etc.) offered such a resource for free I would fully support proliferating that information as widely as possible. 

> How do folks feel just adding "Knative courses" and "Knative videos" there? I think we might want to add a note to the "Knative in action" that states that it requires an email registration?

@vaikas Very few people get to this point in the site, I would recommend putting it elsewhere!

**Comment by omerbensaadon** [comment]
FWIW I agree with @vaikas's approach above, not throwing a wrench in here

**Comment by vaikas** [comment]
@omerbensaadon I'm fine with putting it elsewhere, just when I started adding it, noticed that we already had two books there :)

**Comment by vaikas** [comment]
We have the 'What's next' when you click 'Getting started', so it's one click from the entry page. Should we just add a 'Knative Resources' section that's at the same level as 'What's next' and move the existing links there?

**Comment by julz** [comment]
Completely ack those goals @omerbensaadon and I hope you know I share them! I just don't personally think it's a good look (or gives the impression we want to give, as a project, to potential users, or those considering contributing to or building on the project) to prominently and directly link to a single vendor's branded email capture page from the home page no matter how awesome the book, or how awesome the vendor for sponsoring it. Given that was both @abrennan89's and my reaction, I imagine it would be shared by a fair number of website visitors, too. Being completely honest I don't see a tension between doing what's best to publicise the project and doing what's best to remain vendor neutral here, because I think being/appearing vendor driven and non-neutral would harm us much more than an extra hop to get to the book would help us, and I think we need to be extra cautious of that impression while we remain outside a neutral foundation, but we can agree to disagree here, and as I said I'd defer to steering if they're fine with it.

I don't think anyone has a problem linking to a resources page from the homepage, which seems like a great idea.

**Comment by salaboy** [comment]
@vaikas at least from my personal experience that section is too deep and not easy to find
