### ISSUE TITLE
Broken Link in Event Registry Docs

### ISSUE THREAD

**Issue by JeffNeff** [knative/docs#4092]
## Actual Behavior
The link for `Installing Knative` is broken within the [Event Registry Documentation](https://knative.dev/docs/eventing/event-registry/)
## Steps to Reproduce the Problem

1. Navigate to https://knative.dev/docs/eventing/event-registry/
1. Scroll to the bottom locating the `Next steps` section
1. Select the `Installing Knative` link 

## Additional Info
**Additional context**
n/a

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): Google Chrome
 - Knative Version: n/a

**Comment by abrennan89** [comment]
It actually doesn't make sense for this to be a next step anyway, since this page indirectly has Eventing as a prerequisite.

This link should be removed and a prerequisites section should be added to the page instead.
There's also some other general cleanup here to do, wrt formatting, broken numbering, etc.
