### ISSUE TITLE
Provide 0.25 docs version on knative.dev website

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4117]
We need to add to the drop down `0.25` of the docs (mkdocs based) at the top.

And remove version `0.21`, this version is hugo based
![image](https://user-images.githubusercontent.com/1094878/129786510-b4d50c99-d132-4b23-a528-03c4eb13c261.png)

After this change `0.25`, `0.24`, and `pre-release` will be in mkdocs format. The versions `0.23` and `0.22` will be in hugo format.

**Comment by csantanapr** [comment]
@julz would this something you can handle?

**Comment by julz** [comment]
I can help with this, but it may make sense for me to work with someone else because I did this last release so there's a danger of us ending up with only one person knowing how to release if I keep doing it :) In theory it should be very easy now 🤞 (tho no doubt we'll hit some snags since it's the second time ever)

**Comment by csantanapr** [comment]
I can do it this time for 0.25

Do you have instructions or notes some where?

**Comment by julz** [comment]
These should be the instructions: https://hackmd.io/WWcVF60dT_m4Clv26v8V4w?both (and https://github.com/knative/docs/issues/3978 is the issue to incorporate in to the contributor's guide, which we should do).

I imagine the "edit build.sh on main" step will need a little bit more work than it will in a couple releases (when the Hugo stuff scrolls out) since we still have some hacks in there for the Hugo->mkdocs transition, but shouldn't be super painful and I can help out / do that bit as needed! (We should just be careful to click around the PR preview before merging it).
