### ISSUE TITLE
NATSS channel YAML URL gives a 404

### ISSUE THREAD

**Issue by adamfowleruk** [knative/docs#4159]
## Expected Behavior
YAML URL correct

## Actual Behavior
404

## Steps to Reproduce the Problem

1. Go to page
1. Copy/paste NATS channel kubectl apply command and run it
1. failure

## Additional Info
**Additional context**

Think it should be: https://raw.githubusercontent.com/knative-sandbox/eventing-natss/release-0.25/config/300-natss-channel.yaml

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): EKS
 - Knative Version: 0.25

**Comment by pierDipi** [comment]
cc @zhaojizhuang

**Comment by sebgoa** [comment]
@adamfowleruk which page are you referring to ? If I go to https://knative.dev/docs/eventing/channels/channels-crds/ the NATSS link points to a README file that loads fine.

**Comment by pierDipi** [comment]
Adam is referring to https://knative.dev/docs/admin/install/eventing/install-eventing-with-yaml/, that page links to [1] which should rather be [2] 

1. https://github.com/knative-sandbox/eventing-natss/releases/download/v0.25.0/300-natss-channel.yaml
2. https://github.com/knative-sandbox/eventing-natss/releases/download/v0.25.0/eventing-natss.yaml

This was fixed by https://github.com/knative/docs/pull/4169

/close

**Comment by pierDipi** [comment]
Backport https://github.com/knative/docs/pull/4192
