### ISSUE TITLE
Failing to build Blog locally

### ISSUE THREAD

**Issue by sebgoa** [knative/docs#4427]
I have tried to run the Blog site locally on OSX to fix #4419 

I followed the  instructions in https://knative.dev/docs/help/contributor/mkdocs-contributor-guide/
and ran:

```
./hack/build.sh
```

(submitted a PR #4425  to fix the docs that pointed to an old script)

butI keep running into this issue:

```
Start building sites … 
hugo v0.89.0+extended darwin/amd64 BuildDate=unknown
Error: Error building site: POSTCSS: failed to transform "scss/main.css" (text/css): Error: Loading PostCSS Plugin failed: Cannot find module 'autoprefixer'
Require stack:
- /Users/sebgoa/Documents/gitforks/docs/temp/website/noop.js
```

**Comment by csantanapr** [comment]
@psschwei could look into this?
/assign @psschwei

**Comment by psschwei** [comment]
I was able to get the blog to build on a Mac by running the following commands (let me note that Mac is not my daily driver, so this may not be the ideal way to do things, but it worked...):

```
# clone repo
git clone git@github.com:knative/docs.git
cd docs

# create python virtual environment
python3 -m venv ./venv
source venv/bin/activate
pip install -r requirements.txt

# install npm
brew install npm
npm install -g http-server

#install gnu-sed
brew install gnu-sed
vi ~/.zshrc # add PATH=/usr/local/opt/gnu-sed/libexec/gnubin:$PATH
source ~/.zshrc

# install hugo
brew install hugo

# build website
BUILD_VERSIONS=no ./hack/build.sh serve

# got an error similar to yours, but the one I got mentioned needed to install postcss-cli npm package, so
npm install postcss-cli

# build website again
BUILD_VERSIONS=no ./hack/build.sh serve

# everything a-ok
```

**Comment by julz** [comment]
this happens because we're still building with Hugo for the community section so you need to do `npm install -g postcss postcss-cli autoprefixer http-server` if you're building the whole site (rather than just the mkdocs pages). This is documented in the "**Local Preview including Blog and Community Site" tab** in the [Local Preview section of the contributor guide](https://knative.dev/docs/help/contributor/mkdocs-contributor-guide/#setting-up-local-preview), but it's definitely a little harder to find than would be ideal! (Arguably though given we will be removing the last bit of Hugo soon, this _may_ be ok).

**Comment by sebgoa** [comment]
@julz since you just chimed in, can you check this one https://github.com/knative/docs/pull/4425 because there is an error in the section that you just mentioned

**Comment by sebgoa** [comment]
I will close this, because this is a personal issue. I am now getting down the rabbit hole of having to upgrade my version of OSX...

thanks for the detailed build steps.
