### ISSUE TITLE
Implement new snippet plugin including offset functionality

### ISSUE THREAD

**Issue by snneji** [knative/docs#4556]
## Context

To prevent duplication in docs we want to implement a snippets feature that meets our needs. Do this after #3769 is closed. 

## Tasks

1. Implement the snippets plugin from the result of #3769.
1. Implement the offset functionality for the new plugin so that snippets can be included at the correct heading level in different places. For example, [this one](https://github.com/cmacmackin/markdown-include#configuration).

**Comment by csantanapr** [comment]
I asked in material-mkdocs about it https://github.com/squidfunk/mkdocs-material/discussions/3581

**Comment by abrennan89** [comment]
One of the nice things about asciidoc > markdown+mkdocs is that it provides this out of the box by using leveloffsets with inclusions: https://docs.asciidoctor.org/asciidoc/latest/directives/include/ (no add ons required)

I would still like to keep this on the table for someday future discussion, since I think it still solves a lot more of our wants / needs than markdown.

**Comment by abrennan89** [comment]
Doesn't seem to be anything we can do about this one for now, closing until we find something else we can use, either for mkdocs or move to asciidoc etc.
