### ISSUE TITLE
Add "FAQ" to the knative.dev website

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4668]
We want to add a FAQ page to help users.

Here is the initial set provided by the contractor Lionsway we worked with.

# Frequently Asked Questions (FAQ)

## What is Knative?
Knative is a system that works on top of Kubernetes. It helps development teams manage, monitor, and operate Kubernetes in a way that requires less technical knowledge and time. Knative is open-source, finding support and growth through a combination of individual contributors and industry-leading companies.

## What's the difference between Knative Serving and Knative Eventing?
Knative has two main elements named Knative Serving and Knative Eventing. While they manage different tasks and outcomes and can operate independently, together, they help make Knative a powerful tool for dev teams and IT professionals.
- **Knative Serving** runs serverless containers on Kubernetes with ease. Knative takes care of the details of networking, autoscaling (even to zero), and revision tracking. You have to focus on your core logic.
- **Knative Eventing** allows for universal subscription, delivery, and management of events. Teams can build modern apps by attaching compute to a data stream with declarative event connectivity and a developer-friendly object model.

## Where do I find documentation?
There are two forms of documentation for Knative. First, for end-user and high-level information, you can explore this website. For more granular information, you can see the documents for Knative's three main repositories, [serving](https://github.com/knative/serving/tree/main/docs), [eventing](https://github.com/knative/eventing/tree/main/docs), and [client](https://github.com/knative/client/tree/main/docs).

## How do I find help?
As an open-source project, you can find help by exploring the Knative [documentation](https://github.com/knative/docs) or reaching out to our community through GitHub, [using the tag 'knative' on stackoverflow](https://stackoverflow.com/questions/tagged/knative), and in the community [Slack community](https://slack.knative.dev/) using channels `serving-questions` and `eventing-questions`. The community is very active, and most questions are answered quickly.

## How do I meet the Knative Community?
The community is [very active on GitHub](https://github.com/knative). There is also an active [Knative Slack community](https://slack.knative.dev/) where people swap ideas, talk about improvement, and get help.

## How do I contribute to Knative?
Follow the [knative contributor guide](https://knative.dev/docs/community/contributing/) to get started. You can contribute in many forms like discussions, testing, reporting bugs, code changes, and documentation.

## Do I need to use Istio?
You do not need to use Istio. Knative works with a variety of networking layers. [You can find directions here](https://knative.dev/docs/install/serving/install-serving-with-yaml/#install-a-networking-layer).

**Comment by csantanapr** [comment]
Please comment with questions and answers you want to see on the website, once we have enough of them we can create a PR

**Comment by pmbanugo** [comment]
- Is there a managed cloud version of Knative?
- Who are the contributors or companies backing the project?
- What foundation is it under (CNCF, LF, etc)?

**Comment by csantanapr** [comment]
Good ones @pmbanugo

**Comment by xtreme-sameer-vohra** [comment]
* Who is using Knative ? -> Link to [Adopters](https://github.com/knative/community/blob/main/ADOPTERS.MD)

**Comment by pmbanugo** [comment]
Another question to add. 
- Does Knative support serverless functions?

**Comment by csantanapr** [comment]
FAQ that many websites have, and it seems useful, and many users share the same questions when they are new to the project/technology 

The FAQ should not be a replacement for proper docs, and FAQ can point to specific sections of the docs for a complete answer.

**Comment by abrennan89** [comment]
@csantanapr this article explains my perspective on it as a tech writer https://idratherbewriting.com/2017/06/23/why-tech-writers-hate-faqs/

**Comment by abrennan89** [comment]
We discussed this in the Docs WG call today. Jist as follows:

- Instead of providing an FAQ, which is sort of a jumble of information, all of the suggestions in this issue should have their own clear place in docs where they will be findable for people who are looking for them
- There's already an issue for an About Knative page (https://github.com/knative/docs/issues/4791) which can answer questions about what's supported, components, what foundation is Knative under, etc. per the comments here.
- We will open an additional issue to create a page named something like Adopters (? name needs more discussion probably) that provides info about who is using Knative, case studies, things like managed cloud offerings (since these are not a community thing but might be provided by partners / companies using Knative in products or on their platforms)
- We should open a separate Epic / issue re Istio vs Kourier vs other options, what is required, what isn't, and why users would use one over the other - this should be addressed adequately in the core docs so that it's not a question that's being asked all the time
- All the other "FAQs" in the description of this issue should be obvious from the Knative site as is, and if they're not, it's a bigger issue about our content strategy that will not be solved by adding an FAQ page

I am closing this issue and will be opening an Epic that includes the new issues discussed here, as well as some other topics we talked about on the call today. cc @snneji in case there's anything you'd like to add.
