### ISSUE TITLE
Reference HTML IDs in rendered HTML to facilitate referencing|bookmarks

### ISSUE THREAD

**Issue by DazWilkin** [knative/docs#4725]
**Describe the change you'd like to see**

The API documentation uses HTML IDs, e.g. [RouteStatusFields](https://knative.dev/docs/reference/api/serving-api/#serving.knative.dev/v1.RouteStatusFields):

```HTML
<h3 id="serving.knative.dev/v1.RouteStatusFields">RouteStatusFields</h3>
```

But the HTML ID is not surfaced in the rendered HTML making it cumbersome to grab the ID (from the source) to use it (as I did above).

Curiously, the [Duck Types](https://knative.dev/docs/reference/concepts/duck-typing/) content does this e.g. [Addressable](https://knative.dev/docs/reference/concepts/duck-typing/#addressable) so it may be just config|oversight:

```HTML
<h3 id="addressable">Addressable<a class="headerlink" href="#addressable" title="Permanent link">¶</a></h3>
```

**Additional context**

**Comment by abrennan89** [comment]
@psschwei @evankanderson might you be able to help with this one?
Otherwise I think we would need to close it, since it's not something myself or Samia can do much about, as we didn't create / don't maintain these scripts.

**Comment by evankanderson** [comment]
I think this is "needs eng implementation" -- I'm not sure if there's a "site improvements" bucket for these to go in.

**Comment by abrennan89** [comment]
Added labels for these categories for now

**Comment by psschwei** [comment]
@abrennan89  Based on a quick look, I don't think the problem is the script. Instead, I think the problem is that the serving/eventing API docs are HTML-encoded. For example, here's a small sample from the serving doc:

```markdown
<h2 id="autoscaling.internal.knative.dev/v1alpha1">autoscaling.internal.knative.dev/v1alpha1</h2>
<div>
<p>Package v1alpha1 contains the Autoscaling v1alpha1 API types.</p>
</div>
Resource Types:
<ul><li>
<a href="#autoscaling.internal.knative.dev/v1alpha1.PodAutoscaler">PodAutoscaler</a>
</li></ul>
```

I think all we need to do is remove the HTML tags and convert to markdown formatting, and that should solve the issue. 

Links:
https://github.com/knative/serving/blob/main/docs/serving-api.md?plain=1
https://github.com/knative/eventing/blob/main/docs/eventing-api.md?plain=1

**Comment by psschwei** [comment]
Alternatively, we could just add the links to the existing documents...
