### ISSUE TITLE
Can't run full build locally to test github API rate limit exceeded 

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4930]
We have a script to perform a full build with all versions of the website including the blog, then this build can be served locally to check out any problems.

This is the method that I use to preview the blog edits

When running the command we document
```
./hack/docker/test.sh
```
The user gets errors about github rate limit.

This problem was recently introduced because a GITHUB_TOKEN is now required to do a full build of the website.

We should update the instructions and script to require the env variable GITHUB_TOKEN with the minimal access in the `test.sh` and pass it to the docker container in case someone wants to do a full build locally.

@psschwei 
As for an easy way to preview blog locally, what should we do here?
Maybe create a `blog.sh` or update `run.sh` to add the blog content and we get live preview for blog also

**Comment by psschwei** [comment]
You can build the main branch of the docs and the blog by running `BUILD_VERSIONS=no ./hack/build.sh serve`. I use a python virtual environment instead of docker for local dev, but I image the process should be similar if you wanted to do it in a container...

**Comment by abrennan89** [comment]
@csantanapr @psschwei is there some action to be taken on this issue? I have assigned it to ya'll since I don't think myself or Samia have the expertise to deal with this, nor is it high priority for us vs. other docs work at the moment.

Maybe it should move to the UX repo since it's really about the UX of previewing blogs locally rather than something that can be undertaken by docs WG leads?
