### ISSUE TITLE
Kind Local Development and Private Registries Guide

### ISSUE THREAD

**Issue by dprotaso** [knative/docs#4946]
**Describe the change you'd like to see**
There's a large thread about how to make development with kind+knative easier when using a private registry. https://github.com/knative/serving/issues/6895

The action item was to pull in @csantanapr's content from here: https://github.com/csantanapr/knative-private-images to the docs website

**Comment by dprotaso** [comment]
Note we have: https://knative.dev/docs/serving/deploying-from-private-registry/ where you setup imagePullSecrets/ServiceAccounts.  So a workaround exists - it's sorta a matter of convenience in this specific environment.

**Comment by abrennan89** [comment]
This seems like something that should be a blog post maybe as opposed to part of the core docs. It contains references to a lot of 3rd party stuff like Docker and GCP. 

The reason I didn't want to start including Kind / Minikube in docs is because I always felt like it was going to be a slippery slope that leads us back to documenting vendor-specific workarounds etc when it was agreed a long time ago to remove this sort of thing from the docs.

**Comment by abrennan89** [comment]
As per the above comment, this should be added as a blog post maybe instead of adding to the core docs, since a GCP account is required. Feel free to open a PR to add it as a blog, but I think it's out of scope for core docs issues.
