### ISSUE TITLE
Fix broken quickstart install page

### ISSUE THREAD

**Issue by snneji** [knative/docs#5027]
## Expected Behavior
Installing with quickstart page should have instructions, similar to the [quickstart install page in 1.4](https://knative.dev/v1.4-docs/install/quickstart-install/).

## Actual Behavior
The [installing with quickstart page](https://knative.dev/docs/install/quickstart-install/) has no instructions.

## Steps to Reproduce the Problem
1. Go to the [installing with quickstart page](https://knative.dev/docs/install/quickstart-install/).
1. See that there are no instructions. The only section is "Next steps".

## Additional Info
**Additional context**
This page was a snippet that was also located in the quickstart tutorial section. We added this page to the install section for users who wanted to install Knative using the quickstart plugin outside of they tutorial section.

**Install information:**
 - Knative docs version: 1.5

**Comment by abrennan89** [comment]
My bad, I moved this in https://github.com/knative/docs/pull/4979 because it didn't look like it was used anywhere else. I will fix it.

Related, but do we have some contrib docs about using snippets and to ensure that the places where a snippet is used is listed in the file? This would make it easier to make sure that a snippet is actually being used in more than one place and to easily see all the places where it's in use in the event of changes to a snippet.
