### ISSUE TITLE
code(52) empty reply from server

### ISSUE THREAD

**Issue by jagadhees-ravi** [knative/docs#5280]
Hi,

I am new to knative serving and kubernetes. I have tried deploying helloworld-python app and I followed the instructions as per the document. I can able to build and deploy the app into docker hub. But when I try to give request to the app using curl I am getting this error : **code(52) empty reply from server** . Can you help me with this. My operating system is windows 11. And I am using docker version 4.12.0.

Kindly help me resolve the issue. Thanks in advance

**Comment by abrennan89** [comment]
Presumably this issue is referring to the sample here https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-python

@knative/serving-reviewers @knative/serving-wg-leads can you please reach out to provide guidance here, since these samples aren't maintained by the docs team really. It might be time to look at moving these back into the correct repos, e.g. moving this sample out to the `serving` repo?

@jagadhees-ravi generally it's better to ask questions in the Knative Slack instance or by reaching out to the appropriate WG, rather than logging bugs in the docs repo, since we can't really help with individual issues like this one.

https://slack.knative.dev/
https://knative.dev/docs/contributing/
