### ISSUE TITLE
Error Encountered When Using 'kn quickstart minikube' Command with Knative cli

### ISSUE THREAD

**Issue by AugustasV** [knative/docs#5722]
## Expected Behavior
The `quickstart` command is expected to work as described in the Knative documentation.

## Actual Behavior
When running the `docker` command mentioned in the Knative documentation, an error is encountered. The error message indicates that the `quickstart` command is unknown for the `kn` tool.

## Steps to Reproduce the Problem
1. Run the following command: 
   ```
   docker run --rm -v "$HOME/.kube/config:/root/.kube/config" gcr.io/knative-releases/knative.dev/client/cmd/kn:latest quickstart minikube
   ```
2. Observe the error message: "Error: unknown command 'quickstart' for 'kn'."

## Additional Info
**Additional context**
[Knative Quickstart Installation](https://knative.dev/docs/install/quickstart-install/#run-the-knative-quickstart-plugin).

**Install information:**
- Platform (GKE, IKS, AKS, etc.): Local/Minikube
- Knative Version: v1.11.1

**Comment by Cali0707** [comment]
@AugustasV did you install the quickstart plugin? Quickstart is a separate dependency which must also be added, on top of the core `kn` tool

**Comment by AugustasV** [comment]
Yes now I see... but still to add as a plugin somehow didn't worked as expected on my system. I used `kn-quickstart  minikube`
Why those packages can't be installed with go in simple way something like `go install https://github.com/knative@latest` ?

But Yes my fault, didn't noticed.

**Comment by Cali0707** [comment]
cc @dsimansk @rhuss 

Any ideas about the above question?

**Comment by rhuss** [comment]
/remove-lifecycle stale

Sorry, I'm not deep in the quickstart plugin and so I'm not of great help. @psschwei , maybe you have an idea ?

**Comment by psschwei** [comment]
The preferred ways to install have historically been through either `brew` or downloading the binary from the Github releases page. Using `go get/install` wasn't really considered when we first came up with the idea of the quickstart plugin.

As to why `go install knative.dev/kn-plugin-quickstart` doesn't work, here's what happens when trying to run that command:

```
$ go install knative.dev/kn-plugin-quickstart@latest
go: downloading knative.dev/kn-plugin-quickstart v0.39.1
go: knative.dev/kn-plugin-quickstart@latest: module knative.dev/kn-plugin-quickstart@latest found (v0.39.1), but does not contain package knative.dev/kn-plugin-quickstart
```

If someone wanted to submit a PR to get `go install` working, I'd be happy to help get it merged, but it's not something I personally have the bandwidth these days to tackle.
