### ISSUE TITLE
When is it necessary to skip tag to digest resolving?

### ISSUE THREAD

**Issue by NohaIhab** [knative/docs#5853]
**Describe the change you'd like to see**
In the docs, there are mentions of tag resolution and why it is done in KNative, but there's no mention of when it is needed to [skip tag resolution](https://knative.dev/docs/serving/configuration/deployment/#skipping-tag-resolution). I see many issues in the repo where the solution suggested is to to modify the Serving `config-deployment` configmap to skip tag resolution (examples are https://github.com/knative/serving/issues/13914, https://github.com/knative/serving/issues/6114, https://github.com/knative/serving/issues/9090). The missing information here is what are the use cases when skipping tag resolution is required? or it can be how does tag resolution work so one can understand when they need to skip it?

**Comment by Cali0707** [comment]
@dprotaso @ReToCode any ideas?

**Comment by dprotaso** [comment]
Usually you want to skip it in dev environments - eg. I'm running on kind and I'm preloading images to the the docker vm. Pulling won't work but starting a container will because the image is already on the nodes.

Also some people are using registries with custom ca/self-signed certificates for testing. Rather than configure the controller with the right CA (which we have docs for) people just want to skip this functionality.

Generally it's a bad practice to skip so I don't think we should highlight it.

Let usk now if you have anymore questions.
