### ISSUE TITLE
Eventing source sample in a common languages such as Java/Python/NodeJs

### ISSUE THREAD

**Issue by xinoxapps** [knative/docs#800]
## Problem
The building and serving modules of knative are easy to understand but I'm stuck at the eventing part. 

I was expecting an API like [pub-sub-client](https://cloud.google.com/pubsub/docs/quickstart-client-libraries#pubsub-client-libraries-java) and a simple yaml definition which would fire up the Pod on a given topic.

## Solution
- A complete event sample with a custom publisher and listener.
- Don't write the samples in Go, instead use a popular and well known language such as Java/Python/Javascript (nodejs). 

## How will this impact our users?
- Increase the adaption and understanding of knative.

**Comment by carieshmarie** [comment]
@vaikas-google Do you know if anyone is working on a more end-to-end sample for this?

**Comment by rinormaloku** [comment]
Hi @carieshmarie 

I wrote an example of EventDisplay (from the CountainerSource [guide](https://github.com/knative/docs/blob/master/docs/eventing/samples/container-source/README.md)) in java, here: https://github.com/rinormaloku/event-display-java.

Because this is related to some work that I am doing I could provide the examples, just give me some directions, where to add the examples and is the Container Source use case a good example?
