### ISSUE TITLE
Request to join Knative Org as a Member

### ISSUE THREAD

**Issue by gyliu513** [knative/docs#922]
@samodell as discussed in `February 19, 2019 (4:30pm PT) - Meeting #10` at https://docs.google.com/document/d/1Y7rug0XshcQPdKzptdWbQLQjcjgpFdLeEgP1nfkDAe4/edit#heading=h.abwmqeuzk9ri , can you help figure out how to add me as a Knative Member? Thanks.

**Comment by RichieEscarez** [comment]
oops, sorry

**Comment by samodell** [comment]
Hey @gyliu513 , so the TW team has been discussing this, and we've realized we don't have paths to becoming a contributor for the docs repo specifically well-defined. All the available info is geared towards code contributors. So, before we move forward, we want to customize our paths to reviewer -> contributor specifically for docs, since it requires a different skill set.

On our side, we have a lot of high-priority work at the moment that is taking precedence over this, but our goal is to have more concrete info for you at the next APAC Docs WG, which will be on March 5th. We are super excited that you're interested in contributing to docs, so please be patient as we work this out on our end.

Thanks!

**Comment by samodell** [comment]
Closing this out, since you've been added to the org as a member.
